### ISSUE TITLE
lease read safety

### ISSUE THREAD

**Issue by pifuant** [etcd-io/etcd#10082]
5 nodes(1, 2, 3, 4, 5),  node 1 is leader,  connection of between node 1 and node 5  is break, others is  ok.
       
In node 1(master) lease time, if node 5 triggers leader election and become leader, and then write some data.  it would  break lease read safety,  how did etcd deal with this situation?

**Comment by hexfusion** [comment]
@pifuant let's say we have 5 nodes on term 2 and node 1 is the leader. Although node 5 can communicate with the other nodes it will not receive heartbeat AppendEntries RPC's from leader node 1 and will timeout thus become a candidate and start the election process.

At this time node 5 will increment its term to 3 vote for itself and sends out RequestVote RPCs to the other nodes. Because it can still communicate with a majority of the nodes it could become the leader, which in this case we will assume. Once the remaining nodes increment to term 3 node 1 will remain in term 2 and all requests from it will be rejected by the nodes in term 3.

When the new leader is elected it will reset all lease TTLs to its original value plus `extend` which is basically the election timeout via `lease.Promote`.
https://github.com/etcd-io/etcd/blob/e8b940f268a80c14f7082589f60cbfd3de531d12/lease/lessor.go#L424-L436

https://github.com/etcd-io/etcd/blob/e8b940f268a80c14f7082589f60cbfd3de531d12/etcdserver/server.go#L1959

In v3.4 we will begin to optimize this prevent indefinite auto-renewal (see ref below)

It is important to note that if entries were committed thus replicated to a majority of other nodes while node 1 was the leader and before node 5 was elected then node 5 will not contain all records of term 2 required to be elected in term 3. So, in this case, node 5 will not be voted for by the remaining nodes. You can read section 5.4 of the raft paper for more details on safety.

ref: https://github.com/etcd-io/etcd/pull/9924, https://github.com/etcd-io/etcd/issues/7320, [op-guide: leader-failure](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/failures.md#leader-failure), [raft paper](https://raft.github.io/raft.pdf)

I hope this helps shed a little light on how etcd would handle this situation. Lease data is still safe.

**Comment by pifuant** [comment]
@hexfusion thanks 

Important assumption:  node 1 can't communicate with node 5

Node 1 don't know that node 5 has became leader and don't know TTL reset, because nobody can tell Node 1 all the thing.  Unluckily， if node 1 receives a read request, node 1 just think it is leader  and it will read local data in valid lease time.

**Comment by xiang90** [comment]
> if node 1 receives a read request, node 1 just think it is leader and it will read local data in valid lease time.

no. l-read needs acks from the quorum.

**Comment by pifuant** [comment]
> To use clocks instead of messages for read-only queries, the normal heartbeat mechanism would provide a form of lease [33]. Once the leader’s heartbeats were acknowledged by a majority of the cluster, the leader would assume that no other server will become leader for about an election timeout, and it could extend its lease accordingly (see Figure 6.3). The leader would then reply to read-only queries during that period without any additional communication. (The leadership transfer mechanism presented in Chapter 3 allows the leader to be replaced early; a leader would need to expire its lease before transferring leadership.)

@xiang90   no， node 1 don't need acks from the quorum

**Comment by pifuant** [comment]
@hexfusion @xiang90  please take a look again, I really think raft lease read don't promise safety, unless etcd did extra thing for it.

**Comment by xiang90** [comment]
@pifuant If you have a question about raft's correctness, probably you should start the discussion in the raft mailing list: https://groups.google.com/forum/#!forum/raft-dev

**Comment by pifuant** [comment]
@xiang90 thanks
