### ISSUE TITLE
PUT : [rpc error: code = Unavailable desc = transport is closing]

### ISSUE THREAD

**Issue by bonezhang** [etcd-io/etcd#10179]
1、problem
```
for i := 0; i < 8; i++ {
		var err error
		_, err = cli.Put(ctx, oneNodeKey, "val_old")
		if err != nil {
			fmt.Println("put error ", i, err)
		}

		_, err = cli.Put(ctx, oneNodeKey, "val_new")
		if err != nil {
			fmt.Println("update error ", i, err)
		}

		_, err = cli.Delete(ctx, oneNodeKey)
		if err != nil {
			fmt.Println("delete error", i, err)
		}
		time.Sleep(5 * time.Second)
		//time.Sleep(3 * time.Second)
	}
```
it will work if time sleep > 5 second or < 5 second.  Only Sleep(5 * Second) will report this error.

2、server and client version:
release-3.3

tks

**Comment by jpbetz** [comment]
What error is reported?

**Comment by bonezhang** [comment]
how is progress? @jpbetz

**Comment by spzala** [comment]
@bonezhang hi, I couldn't reproduce it as you have mentioned with the master code. The cause of error as you mentioned is little strange, would you try one more time with the latest code and see if the problem is still around and if so provide more info of your env or we can close this issue. Thanks!

**Comment by chencong-2020** [comment]
i have the same error when i run "etcdctl put" first time at a root user

**Comment by chencong-2020** [comment]
Did you resolve it？
