### ISSUE TITLE
Consider priority during election

### ISSUE THREAD

**Issue by BusyJay** [etcd-io/etcd#10201]
There is a [proposal](https://github.com/pingcap/raft-rs/issues/68) in pingcap/raft-rs that suggests to consider priority during campaign. As it's a general feature, so I also propose it here as @xiang90 suggested.

In short, we may prefer some nodes in cluster be more likely to become leader during campaign due to configuration differences or other consideration. Hence we can add a priority property to every node. A follower votes for a candidate only when one of following prerequisites is met:

- Candidate has more logs;
- Candidate has the same logs and its priority is not less than the follower.

When doing transfer leader, priority may be omitted. For example, it's common to transfer leader before remove leader from configuration. However, there may not be followers that have suitable priority.

The policy is based on an assumption that preferred nodes usually perform better or be deployed in the same near data center. So that such nodes usually catch up logs more quickly than others.

**Comment by siddontang** [comment]
PTAL @xiang90 @bdarnell

**Comment by xiang90** [comment]
@BusyJay 

The priority can be a static number (defined in raft config) or a dynamic one (we can define a priority func in config). 

But I am not sure how priority should be enforced in raft though. A node with higher priority will timeout and try to be candidate faster or a node with higher priority can overwrite the votes for lower priority ones? The later one might break the assumption in raft (wont change vote for one term).

**Comment by bdarnell** [comment]
> But I am not sure how priority should be enforced in raft though.

The proposal is that when a peer receives a MsgVote with a log index that matches its own log, it would only cast the vote if the requesting node has higher priority. Would it then immediately campaign, or wait for its own election timeout to be reached normally?

I expect a rule like this is going to be tricky to get right. If the higher priority follower campaigns immediately at the same term, there may not be enough votes available for it to win. If it increments its term and campaigns, it may disrupt an established leader and interfere with PreVote/CheckQuorum. If it just waits for its timeout, could we get stuck in a case where an election doesn't complete because nodes are waiting for a higher-priority peer to cast a vote? (I think that the latter can happen especially if two nodes have equal priority)

In CockroachDB, we decided to implement leadership priority without modifying the election itself. We allow the election to complete normally, then the new leader can decide (based on its knowledge of the current health of the followers) whether it should transfer leadership to one of them instead. This could also be combined with different timeouts depending on priority so that the transfer is not often needed.

**Comment by BusyJay** [comment]
> ...A node with higher priority will timeout and try to be candidate faster...

@xiang90 It will certainly increase the probability for a preferred node to become leader. However, our tests show that this will work on normal case, but for cases that have unstable network, an unpreferred follower can still become leader easily without rules in the description.

> ...higher priority can overwrite the votes for lower priority ones

I think it's wrong for the same node to vote for two nodes.

> ...Would it then immediately campaign, or wait for its own election timeout to be reached normally?

@bdarnell The proposal only adds a rule to how follower responds a MsgVote. All other mechanisms still work the old way.

The proposal aims to make sure leader be more likely from the preferred nodes and make the cluster more stable under bad network condition combined with prevote.

**Comment by xiang90** [comment]
> In CockroachDB, we decided to implement leadership priority without modifying the election itself.

@bdarnell My unverified assumption: A less preferred node might still be elected, and forwarding read to a less preferred node before leader transfer might affect latency. But this is def a simpler approach, and should be the first thing to try.

What I suggest above is to have a dynamic way to determine the priority. Basically we can define a `canVote()` or `votingPriority()`func interface. And the application can provide an implementation of `canVote` optionally.

**Comment by Grey-Bit** [comment]
@BusyJay was there any progress on this issue?
I also have topological considerations that ask for priority.

**Comment by BusyJay** [comment]
No progress yet. It has low priority on my list. @nolouch Would you like to take over the issue and move forward?

**Comment by BusyJay** [comment]
@xiang90 can this be reopened? I think @dimstars may send a patch soon.

**Comment by spzala** [comment]
> @xiang90 can this be reopened? I think @dimstars may send a patch soon.

@BusyJay thanks, reopened.
