### ISSUE TITLE
During watch ，what may cause Compact_Revision been set except watch a key have been compacted?

### ISSUE THREAD

**Issue by qd19zzx** [etcd-io/etcd#10280]
Hi, I was using jetcd to watch a key, and sometimes we receive compacted exceptions which said "required revision has been compacted". I read the source code of jetcd and found that when the Compact_Revison in WatchResponse from the etcd is not 0, it will occur "required revision has been compacted".
I read the document below:
https://github.com/etcd-io/etcd/blob/34fcabab55585b39835820278da4de65b3463358/Documentation/learning/api.md#watch-streams
It said:
`Compact_Revision - set to the minimum historical revision available to etcd if a watcher tries watching at a compacted revision. This happens when creating a watcher at a compacted revision or the watcher cannot catch up with the progress of the key-value store. The watcher will be canceled; creating new watches with the same start_revision will fail.`
In my understanding, there are two reasons which will cause the Compact_Revision been set:
1. I watch a key which have been compacted
2. The watcher cannot catch up with the progress of the key-value store

I'm sure I watch a key that have not been compacted, but I still receive the WatchResponse which the Compact_Revision have been set. So it must be the second situation. But what is meaning about "The watcher cannot catch up with the progress of the key-value store". In which scenario will cause this situation happen? How can I avoid this? Because when the Compact_Revision is set, the watcher will be canceled as the document said.

**Comment by hexfusion** [comment]
@qd19zzx the best way for us to understand what is happening is to review the etcd server logs around the time of the canceled watcher. Can you provide this? Also, could we take a look at the  watch metrics? You can print metrics with a GET to /metrics endpoint. More detail on the following would be good.
```
etcd_debugging_mvcc_slow_watcher_total
etcd_debugging_mvcc_watcher_total
etcd_debugging_mvcc_watch_stream_total
```
> But what is meaning about "The watcher cannot catch up with the progress of the key-value store".

I believe that this means that the server can not drain events from channel fast enough to client. Because of this these events become labeled as `victim` and we do a batch cancel on them.

https://github.com/etcd-io/etcd/blob/02a9810a9e4e5c95feed4a6d6d2c5525fe2af1c1/mvcc/watchable_store.go#L164-L175

I am also curious if you can reproduce this issue with clientv3 vs jetcd. Perhaps something with the clients watch handling is causing the issue? Could you test that with etcdctl for starters and see if you get the same results? Thanks!

**Comment by hexfusion** [comment]
@qd19zzx also unless you are using jetcd master this is probably relevant https://github.com/etcd-io/jetcd/pull/419 as the async feature has not been released.

**Comment by qd19zzx** [comment]
@hexfusion thank for your reply. Yes, as you said , we didn't use the async feature. In our application, we started a thread to keep watching a key.   
And this exception is reported by our customer, they haven't provided the log from etcd when this exception occurred till now. Anyway, you gave us some indicates to investigate this issue. I think it's very helpful.
And the last question, at first, the snapshot count on their lab is set to 1000.  It is about 10s between two snapshot. In other word, the write rate is 100 writes/s. And the compacted exception happened  very frequently.Then they change the snapshot count to 100000, it's much better. This exception almost disappeared. Do you think the write rate to etcd is too high and the snapshot count is related with this exception？
