### ISSUE TITLE
Question: add member without change the quorum

### ISSUE THREAD

**Issue by JTrotta** [etcd-io/etcd#10329]
Hello,
it's not clear to me if  #3477 or #6420 have been solved.
My problem is that I do not want to increase quorum adding new members. The quorum should be fixed to the initial one, this way an ETCD client can always connects to any alive member and adjusts the lost node membership. 
I'm using CentOS 3.2.22 version

**Comment by hexfusion** [comment]
@JTrotta adding members will increase quorum. We are working on leaner nodes where if you add a new learner they are non voting members and would not increase quorum. These learners can later be promoted to full members.

https://github.com/etcd-io/etcd/blob/master/docs/server-learner.rst

We have also added [--strict-reconfig-check](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#--strict-reconfig-check) This flag will prevent configuration change that would result in loss of quorum. This I believe resolves #3477.

>My problem is that I do not want to increase quorum adding new members. The quorum should be fixed to the initial one, this way an ETCD client can always connects to any alive member and adjusts the lost node membership.

I think in this case the problem is that the current client balancer is not working as expected. We are working to resolve this so if a down node is in the member list client will failover to next member. #6420 is still open but the solution is for etcd server to not add a member who has been misconfigured or not started. This eventually will increase quorum.

**Comment by hexfusion** [comment]
> @hexfusion I understand your points. But does this means that the cluster has no fault tolerance at all?
I mean: if I have 3 nodes clustered and working, I can get data and info connecting a client to whatever node. If one of the 3 nodes goes down, ETCD of other nodes will not answer anymore to clients queries, so fault tolerance, from my point of you, is always zero, or not?

Not sure I follow if you have 3 member cluster and one goes down then the cluster is still quorate. Quorum in a 3 node cluster is 2. So the down node will not respond directly but other 2 members will.

**Comment by JTrotta** [comment]
You're right. With 3 members (2 working, 1 fault) it works. With 2 members the (1 working, 1 fault), it doesn't work.
Thank you.
