### ISSUE TITLE
./etcdctl cluster-health error

### ISSUE THREAD

**Issue by JasonNum1** [etcd-io/etcd#10521]
etcd cluster
enable etcd as follow
in docker-node1:
nohup ./etcd --name docker-node1 --initial-advertise-peer-urls http://192.168.33.11:2380 \
--listen-peer-urls http://192.168.33.11:2380 \
--listen-client-urls http://192.168.33.11:2379,http://127.0.0.1:2379 \
--advertise-client-urls http://192.168.33.11:2379 \
--initial-cluster-token etcd-cluster \
--initial-cluster docker-node1=http://192.168.33.11:2380,docker-node2=http://192.168.192.168.33.12:2380 \
--initial-cluster-state new&

in docker-node2:
nohup ./etcd --name docker-node2 --initial-advertise-peer-urls http://192.168.33.12:2380 \
--listen-peer-urls http://192.168.33.12:2380 \
--listen-client-urls http://192.168.33.12:2379,http://127.0.0.1:2379 \
--advertise-client-urls http://192.168.33.12:2379 \
--initial-cluster-token etcd-cluster \
--initial-cluster docker-node1=http://192.168.33.11:2380,docker-node2=http://192.168.33.12:2380 \
--initial-cluster-state new&

execute "./etcdctl cluster-health"，An error is as follows：
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: client: endpoint http://127.0.0.1:2379 exceeded header timeout
error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused

how can i fix the error

**Comment by hexfusion** [comment]
> execute "./etcdctl cluster-health"，An error is as follows：
cluster may be unhealthy: failed to list members
Error: client: etcd cluster is unavailable or misconfigured
error #0: client: endpoint http://127.0.0.1:2379 exceeded header timeout
error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused

@JasonNum1 first of all `cluster-health` is v2 command, try `endpoint health`. Also notice below you need to pass the  endpoints of the cluster to etcdctl otherwise it will use the defaults which is 127.0.0.1:{2379,4001} for `cluster-health`.
```
ETCDCTL_API=3 etcdctl --endpoints http://192.168.33.12:2379,http://192.168.33.11:2379 endpoint health
```

Please let us know if you still have issues.

**Comment by Boruson** [comment]
ETCDCTL_API=3 etcdctl --endpoints http://192.168.33.12:2379,http://192.168.33.11:2379 endpoint health
if evey etcd-node is heathy ,could it prove etcd-cluster healthy?

**Comment by Boruson** [comment]
ETCDCTL_API=3 etcdctl --endpoints http://192.168.33.12:2379,http://192.168.33.11:2379 endpoint health
sorry, I want to know that:
if evey etcd-node is heathy ,could it prove that etcd-cluster is healthy?
