### ISSUE TITLE
Type mismatch for mirror.NewSyncer when importing "go.etcd.io/etcd/clientv3" 

### ISSUE THREAD

**Issue by peter-klaesson-stratsys** [etcd-io/etcd#10586]
How to reproduce: 
Try compiling the following code (main.go): 

```
package main

import (
	"go.etcd.io/etcd/clientv3"
	"go.etcd.io/etcd/clientv3/mirror"
)

func main() {
	c,_ := clientv3.New(clientv3.Config{})
	s := mirror.NewSyncer(c, "prefix", 0)
}
```
It will give you the error message 
```
.\main.go:10:23: cannot use c (type *"go.etcd.io/etcd/clientv3".Client) as type *"github.com/coreos/ etcd/clientv3".Client in argument to mirror.NewSyncer
```

**Comment by hexfusion** [comment]
This has been discussed but I will also update the docs. If you are using `go mod` you need to vendor and import `github.com/coreos/etcd`. This is because etcd 3.3.x is basically the past and used the old org which we can not change. When we cut etcd 3.4 we will officially move to the new org and `go.etcd.io/etcd/clientv3` will be valid.
