### ISSUE TITLE
raft: Seems like dead link

### ISSUE THREAD

**Issue by nilsocket** [etcd-io/etcd#10831]
In this folder, https://github.com/etcd-io/etcd/tree/master/raft

In readme, this seems to be a dead link, in last paragraph
https://ramcloud.stanford.edu/~ongaro/thesis.pdf

Thank you.

**Comment by spzala** [comment]
Yes, it seems not accessible anymore. Earlier, https://github.com/etcd-io/etcd/pull/10704 fixed the deprecated raft paper links. We should remove the link, if we couldn't find one for the thesis. (this will leave it just mentioning of thesis in a similar way as done in the README under Usage section `as explained at section 10.2.1 in Raft thesis` - https://github.com/etcd-io/etcd/tree/master/raft#usage ) Thanks!

**Comment by nilsocket** [comment]
@spzala Aren't pdf's in this link valid, or else were they outdated.

Thank you.

**Comment by spzala** [comment]
@nilsocket I couldn't open the pdf and as I mentioned under the PR https://github.com/etcd-io/etcd/pull/10704 the paper that was hosted on ramcloud.stanford.edu were replaced because it wasn't accessible. For now, if you are interested in looking at thesis I believe the material at https://github.com/ongardie/dissertation should be helpful. (In the doc, we should remove or replace the link) Thanks! 
/cc @xiang90

**Comment by spzala** [comment]
Fixed. @nilsocket closing it. Thanks again for reporting!
