### ISSUE TITLE
etcdserver: a read instruction to a field may need be protected

### ISSUE THREAD

**Issue by lzhfromustc** [etcd-io/etcd#10871]
### Summary
There is a small inconsistency in code, but potentially a threat in the future.
### Location
In [etcdserver/server.go](https://github.com/etcd-io/etcd/blob/master/etcdserver/server.go), there are a few usages of `s.be`:
```Go
// line 1112 to 1294:
func (s *EtcdServer) applySnapshot(ep *etcdProgress, apply *apply) {
	...//some irrelevant code

	s.bemu.Lock()
	oldbe := s.be
	go func() {
	...//some code to close oldbe
	}()
	s.be = newbe
	s.bemu.Unlock()

	...//some code to handle error

	s.cluster.SetBackend(s.be)

	...//some irrelevant code
}

//line 2579 to 2583:
func (s *EtcdServer) Backend() backend.Backend {
	s.bemu.Lock()
	defer s.bemu.Unlock()
	return s.be
}
```
As you can see above, in this package, `s.be` is always protected by `s.bemu`, except the line at 1294:`s.cluster.SetBackend(s.be)` 
### Discussion
I think in current version there is no data race, because in every goroutine, the parent `applySnapshot` is only called once.

However, the inconsistency may produce problems in the future. If someone didn't realize `s.cluster.SetBackend(s.be)` was not protected and called `applySnapshot` in multiple goroutines, the race would happen.
### Suggestion
I think we can just put a "defer" before `s.bemu.Unlock`

**Comment by spzala** [comment]
@lzhfromustc thanks for reporting, would you like to create a PR with your proposed fix? That way, it can be reviewed efficiently and we know how build run against the changes. Thanks!

**Comment by lzhfromustc** [comment]
Sure, I will open a PR shortly.
I am not very familiar with contributing. Could you tell me if my following understanding is correct?
(1) If I find a bug or bad practice, and I am quite confident about how to fix it, I will request a PR directly without opening a new issue.
(2) If I find a bug or bad practice, but I don't know if it is really worthy of fixing or how to fix it, I will open a new issue.

**Comment by spzala** [comment]
> Sure, I will open a PR shortly.
> I am not very familiar with contributing. Could you tell me if my following understanding is correct?
> (1) If I find a bug or bad practice, and I am quite confident about how to fix it, I will request a PR directly without opening a new issue.
> (2) If I find a bug or bad practice, but I don't know if it is really worthy of fixing or how to fix it, I will open a new issue.

Thanks @lzhfromustc  there are no hard rules. You can create a PR directly without opening an issue (in that case you would provide details in PR itself) or you can create an issue and provide a PR for it by mentioning the issue in the PR description. If an issue reporter is not a developer or can't provide a PR, just reporting an issue is totally fine. The community is friendly and helpful. In this particular issue, because you are proposing a code change, creating a PR is makes more sense for the reasons I mentioned previously. Here is a doc link on contribution - https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#how-to-contribute Let me know if you have any question.

**Comment by lzhfromustc** [comment]
Thank you for your detailed explanation! It feels good to be helpful to the community.
I have requested [a PR](https://github.com/etcd-io/etcd/pull/10874) and referenced this issue.
