### ISSUE TITLE
Best practices for maintaining etcd HA

### ISSUE THREAD

**Issue by exue026** [etcd-io/etcd#10991]
I would like some advice on best practices for ensuring the availability of a robust etcd cluster deployed in production. I've tried my best to read through all the documentation in this repo, but the only thing I could find is from the document on [runtime configuration](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/runtime-configuration.md). It describes that if a node fails (and quorum still exists), that we should "replace the machine, [and] follow the instructions for removing the member from the cluster, and then add a new member in its place."

My question is: why do we manually have to handle this failure mode? Is it not possible for etcd to detect internally that one of its members has gone down and automatically restart it? If this is not possible, what would be a recommended implementation to solve this problem? Would we need to create some service that monitors the health of each node, and then programmatically remove/add a node through  `etcdctl` if one goes down?

**Comment by hexfusion** [comment]
> Is it not possible for etcd to detect internally that one of its members has gone down and automatically restart it? 

A simple health check can restart the member if it is down. But in a failure mode like corruption restarting will not help. Management of this type of workflow is best handled by external logic, for example, an operator.

**Comment by exue026** [comment]
Thank you for the information @hexfusion . One more question though: if you must add external logic and have some sort of operator that monitors the health of the cluster, how does that contribute to the fault-tolerance of etcd? Wouldn't that introduce another point of failure? The goal is to monitor and restart etcd nodes if need be, but what if the operator itself goes down?

**Comment by hexfusion** [comment]
> One more question though: if you must add external logic and have some sort of operator that monitors the health of the cluster, how does that contribute to the fault-tolerance of etcd?

I never said that you need an operator to check health my point above is that restarting can help you escape something simple like OOM which took down etcd under stress but if the member needs **replaced** like for example data corruption etcd does not know about its own ENV.

For example, if etcd is deployed as a Pod. How can etcd know that it is in a Pod deployed via k8s on a specific cloud provider? How can it know how to generate new certificates for the peer that it wants to replace and how to deploy the new member that failed? What is the IP address of the new member? These are things that require human operator knowledge right? If etcd sees a member down because of say a network partition how does it tell that peer to restart? If it restarts itself under partition is the cluster more healthy? The list of these corner cases is long.

**Comment by exue026** [comment]
Ah I see, thanks for the clarification!
