### ISSUE TITLE
Is it possible to change configure param such as auto-compaction-retention when etcd is running?

### ISSUE THREAD

**Issue by JalySN** [etcd-io/etcd#11171]
The etcd cluster is running, but the mvcc database space nearly exceeded.

How to reload configure file or add _auto-compaction-retention_ when etcd is running?

**Comment by WIZARD-CXY** [comment]
now is not possible

**Comment by birdman7260** [comment]
@WIZARD-CXY is it possible to enable auto-compaction by updating the configuration of each member one at a time? As in stopping a member, updating the flags to include the `auto-compaction-retention`, starting the member again and moving through the entire cluster?

I'm trying to do this with one of my clusters but it doesn't seem to be taking effect since I'm not  seeing anything about it in the logs. This is confusing because I've increased the `quota-backend-bytes` using the above strategy and it definitely appears to work since the first time I changed it beyond the recommended limit of 8GB and I could see warnings in the logs, though now I have doubts about it actually taking effect...

**Comment by WIZARD-CXY** [comment]
@birdman7260 it should work. Did you change the whole cluster's settings `auto-compaction-retention` ? Now the compact is a leader work if I remember right. So you must change the whole cluster and wait a while to let the old compaction done.

**Comment by birdman7260** [comment]
@WIZARD-CXY ah you're right! I was changing the settings from the default values (which from my understanding is 0 and therefore there is no auto-compaction by default, at least on our version 3.3.12) and after a few hours I wasn't seeing it in the logs but today I checked and it now is running properly :)

I changed it to have these settings:
```
  --auto-compaction-mode=periodic \
  --auto-compaction-retention=10h \```
with the intention of having it run every hour. Do you happen to know if it was just waiting 10 hours first before doing the scheduled compaction?

**Comment by WIZARD-CXY** [comment]
@birdman7260 From the changelog if I remember correct  it will wait an hour.

**Comment by jingyih** [comment]
@birdman7260 Regarding the logic of the periodic compactor, you can refer to the description here:

https://github.com/etcd-io/etcd/blob/b852e37895e7ddd36816c0f4f76e281d50551cb3/etcdserver/api/v3compactor/periodic.go#L63-L95
