### ISSUE TITLE
Improve embed logging options

### ISSUE THREAD

**Issue by diegobernardes** [etcd-io/etcd#11390]
It's awesome that Etcd has official embed support. It's really working great for a project that I'm working on but it could be even better if we had more options to configure the logger.

What you guys think in add at the `embed.Config` an option to change the logger writer. With that, we can plug Etcd log output into any other logger system (file, logrus, zap, zerolog, etc...).

**Comment by xiang90** [comment]
seems like a good idea. what would that logger api look like?

**Comment by siddontang** [comment]
maybe you can define a similar one in etcd like https://github.com/birkirb/loggers/blob/master/loggers.go

I think these interfaces are easy to be intergrated with current logger system.

**Comment by diegobernardes** [comment]
Sorry the late reply. My idea was to provide a `io.Writer` at the configuration struct. The Etcd logger should use this writer.

This gives the flexibility to the caller to discard the logs with something like `ioutil.Discard` or create a custom writer interface to send the logs to other logger like `zerolog`, `logrus`, etc...

**Comment by gyuho** [comment]
Currently, we only support file paths via `--log-outputs` flag (also available via `LogOutputs`). And `zap` does not support `io.Writer` in the `zap.Config.OutputPaths` fields.

**Comment by diegobernardes** [comment]
It's possible with [NewCore](https://godoc.org/go.uber.org/zap/zapcore#NewCore) as it accepts a [interface](https://godoc.org/go.uber.org/zap/zapcore#WriteSyncer).

Don't know about the effort, but would be a nice option for embedded uses. More information [here](https://godoc.org/go.uber.org/zap#hdr-Extending_Zap).

**Comment by purpleidea** [comment]
I just moved https://github.com/purpleidea/mgmt/ to etcd 3.4.x (it embeds etcd via embed) so I had to move away from capnslog to zap, but as mentioned, there's no way to pass in my own logging method.

Ideally I'd pass in something like `func(format string, v ...interface{}) {` but of course any _io.*_ sort of thing will do too.

In the meantime, I had to disable all the logging because otherwise I got a firehose of etcd messages. This is how I did it:

https://github.com/purpleidea/mgmt/commit/f0aa96ea8cdf6f3b59739a248341f577326056c7

Note while reading the code, it's seemingly not possible to use the `ZapLoggerBuilder` in embed AFAICT because the needed methods inside Config are private.

So this is definitely something that would be incredibly useful. If someone writes a patch, please ping me I'm happy to review.

Thanks!

**Comment by purpleidea** [comment]
This is still not possible and pretty important... Can we keep this open please?

**Comment by cretz** [comment]
Concur, can this please be reopened?

**Comment by liujiang0529** [comment]
> Currently, we only support file paths via `--log-outputs` flag (also available via `LogOutputs`). And `zap` does not support `io.Writer` in the `zap.Config.OutputPaths` fields.

is the item  `--log-outputs`  support the log to the file? why i set "logger: zap, log-outputs: [/root/DCS/GMDB/package/etcd/etcdlogtest/]",when i run with it ,why  no log file create in the dir?
