### ISSUE TITLE
took too long to execute

### ISSUE THREAD

**Issue by Belyenochi** [etcd-io/etcd#11501]
[description]
Why do etcd occasionally report read-only range request when the disk performance is up to standard? The etcd fsync took too long to execute and shot up to 100ms, but the corresponding disk IOPS were unchanged. Disk utilization was 13% (usually 0.5%), there was no queue extrusion on the disk, CPU utilization was less than 10%, and network traffic was not significantly changed.

[env]
etcd v3.2.24 v3.2.28 v3.4.3
linux 4.19.1-1.e17.elrepo.x86_64

[question]
1. Why did the read only error occur
2. Why is the reelection triggered

**Comment by Belyenochi** [comment]
![0669397D-ED7A-4aaf-B212-06D67DBF4BFE](https://user-images.githubusercontent.com/26409132/71873472-3a1cb900-315a-11ea-832b-55abe9c656dc.png)
![6186A3D3-3F41-468c-9DD8-22E78574603D](https://user-images.githubusercontent.com/26409132/71873473-3a1cb900-315a-11ea-8b2a-03181b614dfc.png)

**Comment by Belyenochi** [comment]
![A272782A-E34F-4e5b-B10F-183732DC95C7](https://user-images.githubusercontent.com/26409132/71873785-068e5e80-315b-11ea-8c78-c23cc1c1e348.png)

**Comment by xiang90** [comment]
If you looked at your log, leader election kept on happening which affected the overall latency of all requests. Normally it is due to a unstable network situation.

For disk IO, IO throughput might not mean that much for etcd but latency does matter. So you need to measure IO request latency first.
