### ISSUE TITLE
Better document clientv3 retry clients

### ISSUE THREAD

**Issue by jacobcase** [etcd-io/etcd#11567]
I'm currently going through the godoc for clientv3 and I'm having a hard time understanding the retry behavior for the various clients by simply skimming code for retry_interceptor.go as someone who is very new to grpc internals. Having better godoc around the retry client would be useful to understand the behavior. Additionally, it doesn't appear by looking at the API that the retry behavior is very customizable (backoff, retry count, jitter, etc). If I'm missing how to do this, perhaps there could be some examples? 

Side note, bug reporting message "Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md." link is broken.

Thank you for the help!

**Comment by xiang90** [comment]
The retry thing was designed before grpc retry was proposed and implemented (https://github.com/grpc/proposal/blob/master/A6-client-retries.md).

It is complicated since we want to overcome some inflexibilities of gRPC at the time. I guess gRPC is much better now... Probably we should revisit the whole retry thing and make it better defined.

@jacobcase as you already looked into the code, do you want to help on this effort?

**Comment by spzala** [comment]
@jacobcase a very recent restructuring on the doc created few broken links (including the one you mentioned) but it's known and they will be fixed soon as part of the ongoing work. Thanks! /cc @lucperkins
