### ISSUE TITLE
Etcd encodes unix socket path for peers listening

### ISSUE THREAD

**Issue by DenisRazinkin** [etcd-io/etcd#12023]
-bash-4.4# etcd --version
etcd Version: 3.3.18
Git SHA: 3c8740a79
Go Version: go1.12.9
Go OS/Arch: linux/amd64

Start etcd with command:
-bash-4.4# etcd --listen-peer-urls=unix://node1:2380 --listen-client-urls=unix://node1:2379 --advertise-client-urls=unix://node1:2379

-bash-4.4# netstat -lpx | grep etcd
unix  2      [ ACC ]     STREAM     LISTENING     2947964  11886/etcd           node1:2379
unix  2      [ ACC ]     STREAM     LISTENING     2947963  11886/etcd           @02f03

Why has etcd replaced original path node1:2380 with something looks like a hash value?

**Comment by cfc4n** [comment]
assign @cfc4n 

/cc @gyuho @xiang90

**Comment by cfc4n** [comment]
I can reproduce. but the shell was
```
[root@cnxct-etcd etcd]# bin/etcd

[root@cnxct-etcd ~]# netstat -lapx |grep etcd
unix  2      [ ]         DGRAM                    35506    11255/bin/etcd       @00042
```
and I found the rootcause. 

All of them who import `github.com/coreos/etcd/pkg/logutil` will reproduce it. It means that `etcd`\`etcdctl`  will listen `@000***` **[abstract unix socket](https://www.man7.org/linux/man-pages/man7/unix.7.html)**  address.

Because `github.com/coreos/etcd/pkg/logutil` import `github.com/coreos/go-systemd/journal`.
The function name `initConn` in [journal/journal.go](https://github.com/coreos/go-systemd/blob/b51e752dd1c9c618846f8bc5b95ab524bd7b11c2/journal/journal.go#L210-225) Line 210-225 :
```
// initConn initializes the global `unixConnPtr` socket.
// It is meant to be called exactly once, at program startup.
func initConn() {
	autobind, err := net.ResolveUnixAddr("unixgram", "")
	if err != nil {
		return
	}

	sock, err := net.ListenUnixgram("unixgram", autobind)
	if err != nil {
		return
	}

	atomic.StorePointer(&unixConnPtr, unsafe.Pointer(sock))
}
```

This function will listen unixgram socket with empty address. So you will see that an address begin with `@` , and other numbers append. 

Here is debug stack,:
```
/usr/local/go1.12.9/go/src/net/unixsock_posix.go:21 +0x12c
net.(*sysListener).listenUnixgram(0xc000061e70, 0x1133820, 0xc000034110, 0xc00000c560, 0x192d000, 0x7f776fad6008, 0x0)
	/usr/local/go1.12.9/go/src/net/unixsock_posix.go:222 +0x9a
net.ListenUnixgram(0xfa8300, 0x8, 0xc00000c560, 0xc000061ef8, 0x10, 0xc000061ef0)
	/usr/local/go1.12.9/go/src/net/unixsock.go:347 +0xe1
github.com/coreos/go-systemd/journal.initConn()
	/root/cfc4n/gopath/pkg/mod/github.com/coreos/go-systemd@v0.0.0-20190620071333-e64a0ec8b42a/journal/journal.go:219 +0xb6
sync.(*Once).Do(0x1949010, 0xfee170)
	/usr/local/go1.12.9/go/src/sync/once.go:44 +0xb3
github.com/coreos/go-systemd/journal.init.0()
	/root/cfc4n/gopath/pkg/mod/github.com/coreos/go-systemd@v0.0.0-20190620071333-e64a0ec8b42a/journal/journal.go:69 +0x39
```

# conclusion
It is not a bug of etcd, But i don't know why does it do that. Maybe you can send a issue in [go-systemd](https://github.com/coreos/go-systemd/issues)
😄 

@xiang90  Please close this issue,thanks.

**Comment by Denis-Razinkin** [comment]
So, then why does the client listener open socket using correct path? 
As far as I understand both listeners types use func 
```
func NewUnixListener(addr string) (net.Listener, error) {
	if err := os.Remove(addr); err != nil && !os.IsNotExist(err) {
		return nil, err
	}
	l, err := net.Listen("unix", addr)
	if err != nil {
		return nil, err
	}
	return &unixListener{l}, nil
}
```
from [pkg/transport/unix_listener.go](https://github.com/etcd-io/etcd/blob/master/pkg/transport/unix_listener.go)
Isn't it?

**Comment by Denis-Razinkin** [comment]
Could not reproduce in last release version:

**Comment by Denis-Razinkin** [comment]
Sorry for false alarm, may close issue
I have merged in local etcd repo copy unapproved [pull request,](https://github.com/etcd-io/etcd/pull/11747) that cause this error
