### ISSUE TITLE
ETCD client package for v3.4

### ISSUE THREAD

**Issue by jasiu001** [etcd-io/etcd#12258]
I am trying to use the latest etcd go client in my project. According to repository last version is v3.4.13, but it is not available on [pkg.go.dev](https://pkg.go.dev/go.etcd.io/etcd/clientv3?tab=versions). There the last version is still v3.3, so I have a question how can I use in my project base on go module etcd go client version 3.4?
Do I have to wait until it will be available on pkg.go.dev? How long it will take?

**Comment by cupen** [comment]
@jasiu001 I meet the same problem.  it's beacuse grpc has some breaking changes. 
Look at my point, hope it's helpful for you.
https://github.com/etcd-io/etcd/issues/12276#issuecomment-689368903

**Comment by Hendrik-H** [comment]
I used the approach outlined here: https://github.com/etcd-io/etcd/issues/11154#issuecomment-568587798
Just take the taged version you want to have. Works pretty well for me. So for `v3.4.13` that would be `v0.0.0-20200824191128-ae9734ed278b`. I also had to make sure to use at least go 1.14 and `google.golang.org/grpc v1.29.0` due to https://github.com/etcd-io/etcd/issues/12124.

**Comment by swdee** [comment]
I made a standalone clientv3 package based on v3.4.13 as a temporary solution until v3.5 comes out when hopefully these Go Module and GRPC version issues are resolved.   https://github.com/swdee/etcdc
