### ISSUE TITLE
Is there a way to take a snapshot only the latest version of etcd store?

### ISSUE THREAD

**Issue by sridhav** [etcd-io/etcd#12500]
We want to save the snapshots only the latest version of our etcd store ignoring all previous versions. Is there a way with etcdctl to do this? If there isn't one I will be more than happy to contribute to it. Thanks!

**Comment by ptabor** [comment]
I'm not aware of such method. 
Why not to compact and then to snapshot ? Do you care about history on the server ?

**Comment by sridhav** [comment]
@ptabor we are taking 15min backups and are only interested in latest versions. Running compaction every 15mins feels a bit overwhelming on the server. 

Also we want to decrease our backup sizes as we use it only during disaster recovery. We like to have few revisions on our server

**Comment by ptabor** [comment]
Kubernetes is doing compaction every 5 minutes by default: 
  https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

Etcd can be configured to perform compaction automatically with given interval. So I would expect investment towards making compaction even 'lighter' rather than in-flight compaction of snapshots.
