### ISSUE TITLE
crash when watching

### ISSUE THREAD

**Issue by star2sea** [etcd-io/etcd#12532]
Hello，i run a goroutine for watching etcd，i wanna know that when the etcd crash，how does the watching goroutine know that   ？Please give me an answer, thanks very much!

**Comment by agargi** [comment]
AFAIK, there is no way since etcd failure may be transient in nature and from client's perspective, it is not possible to distinguish between transient and permanent failures. Onus is on client to detect failures and accordingly respond.

If client wants, it can always cancel the context which will make it come out of watch channel loop.

**Comment by xiang90** [comment]
closing since @agargi's answer is correct.
