### ISSUE TITLE
raft: larger id size

### ISSUE THREAD

**Issue by aep** [etcd-io/etcd#12581]
Would it be possible to extend the size of the node id?

8 byte is a bit challenging, because they must not collide, yet be generated _before_ joining the cluster.
16 bit UUIDs are generally considered reasonably collision free, although i'd need 32byte for ed25519

maybe i'm missing it, but i can't find any specific reason in the paper that limits the size to 8 byte

**Comment by ptabor** [comment]
Probability of collisions start to exceed 50% after 2^32 node's being generated. 
Additional protecting is offered by cluster_id that would also need to conflict (with its own 2^32). 

The flip-side of longer identifiers is performance (e.g. you need to process them as 'bytes' instead of CPU words).

Please describe a scenario in which you are  afraid of the conflicts.
