### ISSUE TITLE
Ideas for multi-boltdb backends support

### ISSUE THREAD

**Issue by wilsonwang371** [etcd-io/etcd#12924]
@ptabor @gyuho 

Hi guys,

I have an idea about possible performance improvement in etcd.

Do you think using multiple boltdb backend instances will make some difference in the performance?

From the tracing graph, we can see that whenever backend run() is executing, very few other goroutines can execute and if we can reduce this period of time, we may get some further performance improvement.

![image](https://user-images.githubusercontent.com/3913185/117500236-2e4d2c80-af31-11eb-8acd-ed3767fd591e.png)

Do you guys have any concerns or suggestions?

**Comment by ptabor** [comment]
Instead of using multiple bolts, I would think how to make "better bolt" (tm). 

I would recommend exploring 2 directions: 

## Write pages ASAP (optimistically) 

It seems to me that bbolt starts 'write' of pages to disk when the transaction is committed: 
https://github.com/etcd-io/bbolt/blob/90fdc8d162431506d5fec5b199501ad86f5e15e6/tx.go#L537

Taking in consideration that: 
  - etcd does not rollbacks the transactions (as these are 'batch' commits)
  - the page is really relevant if it's linked from the 'parents' page (or is a root page). 
  - etcd usually keeps appending to a 'last' page rather then doing random edits on set of pages 

I think bbolt for etcd should: 
  - start writing `leaf` pages to disk as soon as they are full  (even before commit was called). 
  - maybe even write `parents' and 'grant parants' of the leaf pages as soon as they modified. 
  - successful commit should: 
       - write the free-pages index
       - write the 'root' page (and maybe a few top level branch pages').
       - maybe 'flush'
  - rolled back commit should return all the written pages back to the free pages list and do NOT modify the root page. 

It should make the disk usage way more 'uniform' and commit locks substantially shorter. 

## Do not (block) on fsync in bolt layer

From DB theory standpoint in etcd. data are persistent as soon as: 
  1. WAL log was written and is fsynced
  2. RAFT declared the transaction as 'committed' 
  
The bbolt strong (fsynced) persistance is only needed for etcd/RAFT snapshots that are relatively infrequent, 
i.e. when snapshot happens, we need to be sure that the fsynced bbolt's applied_index is not older than the snapshot's commit index.

**Comment by xiang90** [comment]
@ptabor 

Yes, if we want to improve the write path latency + throughput we should try these two first. 

In terms of performance and scale, the other dimensions are delta encoding of values, incremental snapshot transmission, more adaptive and non-blocking compaction, and faster recovery time.

**Comment by wilsonwang371** [comment]
> Instead of using multiple bolts, I would think how to make "better bolt" (tm).
> 
> I would recommend exploring 2 directions:
> 
> ## Write pages ASAP (optimistically)
> It seems to me that bbolt starts 'write' of pages to disk when the transaction is committed:
> https://github.com/etcd-io/bbolt/blob/90fdc8d162431506d5fec5b199501ad86f5e15e6/tx.go#L537
> 
> Taking in consideration that:
> 
> * etcd does not rollbacks the transactions (as these are 'batch' commits)
> * the page is really relevant if it's linked from the 'parents' page (or is a root page).
> * etcd usually keeps appending to a 'last' page rather then doing random edits on set of pages
> 
> I think bbolt for etcd should:
> 
> * start writing `leaf` pages to disk as soon as they are full  (even before commit was called).
> * maybe even write `parents' and 'grant parants' of the leaf pages as soon as they modified.
> * successful commit should:
>   
>   * write the free-pages index
>   * write the 'root' page (and maybe a few top level branch pages').
>   * maybe 'flush'
> * rolled back commit should return all the written pages back to the free pages list and do NOT modify the root page.
> 
> It should make the disk usage way more 'uniform' and commit locks substantially shorter.
> 
> ## Do not (block) on fsync in bolt layer
> From DB theory standpoint in etcd. data are persistent as soon as:
> 
> 1. WAL log was written and is fsynced
> 2. RAFT declared the transaction as 'committed'
> 
> The bbolt strong (fsynced) persistance is only needed for etcd/RAFT snapshots that are relatively infrequent,
> i.e. when snapshot happens, we need to be sure that the fsynced bbolt's applied_index is not older than the snapshot's commit index.

Nice comment! Do we have this information documented somewhere. I think this should be known by every contributor.
