### ISSUE TITLE
scripts/genproto.sh: updates needed

### ISSUE THREAD

**Issue by chalin** [etcd-io/etcd#13050]
The API-reference generator needs a few updates to:

- [ ] Match the changes mentioned in https://github.com/etcd-io/website/issues/330.
- [ ] Generate page front matter
- [ ] Reconsider where the output should go: currently, the script is targeting `Documentation/dev-guide/api_concurrency_reference_v3.md`. The website docs aren't under `Documentation` anymore. Either the output target should be changed, or instructions should be given to let the script user know where to copy/submit the files to.
- As a followup action, port to the release-3.5 branch

cc @nate-double-u @gyuho

**Comment by danishprakash** [comment]
@chalin would like to pick this up

**Comment by nate-double-u** [comment]
I'd actually like to take a shot at this if I could :)
/assign @nate-double-u

**Comment by nate-double-u** [comment]
I'd like to move the files, and am happy to have them land in the root folder where the script needs to be run from.
I'd also suggest adding them to the `.gitignore` file so that they aren't accidentally committed to this repo after generation.

Should we add instructions regarding what to do with these two files after generation regardless of whether their generation output is moved?

**Comment by chalin** [comment]
Thanks for the offer @danishprakash, but I had already asked @nate-double-u (since he had made the corresponding doc changes).

**Comment by chalin** [comment]
I'm thinking that we should get the doc changes in first before we consider moving the files. I agree about adding / printing instructions in the meantime.
