### ISSUE TITLE
Backup of etcd EBS volumes

### ISSUE THREAD

**Issue by tkoeck** [etcd-io/etcd#13136]
Hi,

we use AWS EBS snapshots to backup our Kubernetes etcd volumes. That worked so far but I am wondering if we cannot possibly get rare problems with that approach and should backup it in another way.

- Is it possible to use volume snapshots to backup etcd volumes without possibly corruption the recovered data?
- Can etcd recover from a created volume from a snapshot? Especially when you assume transaction security (ACID) in etcd?

**Comment by obockows** [comment]
@mumoshu was trying to answer it in https://github.com/kubernetes/kubernetes/issues/40027#issuecomment-288930752
IMHO there are 3 approaches to restore, 1 &2  are rather ok and 3rd is tricky. I will use the example of upgrades (because in the Ops world it is common to use a disk snapshot before patching)

1. Rolling master upgrade, e.g. when we fully update one master and process with next. Procedure: shutdown one node, take disk snapshot, startup, upgrade, in case of failure stop it and revert. It works without any issues and it’s straightforward, after a start, the node join clusters as “follower”, gets heartbeat (RPC appendEntries from Leader), and remain with the state: “follower”  

2. Shutdown all masters, take disk snapshot - we shutdown all masters at once. Take snapshots, turn on, upgrade, in case of a failure, we shut down and restore. 
Looking from the RAFT point of view, it is rather ok and the order of starting up masters won't affect anything. There will always be 2 masters with the same term numbers and committed entries so 3rd one won’t win the election. 

NOTE: 2 & 3 will work thanks to the RAFT leader election and the election restriction.

3. Shutdown masters one by one and take 3 snapshots: in general it’s the riskiest scenario and data could be lost. It’s appealing because it gives the availability of the control plane. We shutdown master1, take a snapshot, start it, the same with master2 and the same with master3. We end up with 3 snapshots, between each of them there could be some changes.  
That process is tricky because after the restoration, the order of the boot process is important and we should monitor the leader role as well.

EXAMPLE:

Master1, master2, master3 (leader). In logs, we have the last “entry” written in term 1, index 11. Shutdown master1, disk snapshot, start back.  Changes, a new entry is written in term 1, index 12, committed. Shutdown master2, snapshot, start it back. Changes, a new entry is written again, still, term 1, index 13, shutdown master3, snapshot, start it back. Other activities, a failure, power off all, restore from disk snapshots and if we start master3 with master1 or master2, that’s ok. We have term2, RPC RequestVote from master1/master2 will be denied by master3 (due to “election restriction”). In the case of RequestVote from master3, it will be accepted and we have the quorum. 

If we start master1 and master2 first, master2 will be elected as leader, they have a quorum, master3 joins and its log should be overwritten, or even there will be some failure. It could be even more problematic if the scenario had been different, e.g. master3 comes with a higher RAFT Term (due to some changes between snapshots), the “In Search of an Understandable  Consensus Algorithm” doc doesn’t consider such unusual circumstances even.

@gyuho  could you give us your thoughts? I afraid I could miss something important due to my limited knowledge about RAFT.

**Comment by tkoeck** [comment]
Thanks for the advice. I will look into it.

We are creating automatic EBS snapshot every two hours. Shutting down all masters at once would be tricky. Especially when Kubernetes services should run while doing that.

**Comment by agargi** [comment]
@obockows Sorry did not quite understand approach 3 (and difference between this and approach 1) since Approach 1 is rolling master upgrade (which should give high availability) but its mentioned as true for 3 too. And 3 seems to be rolling upgrade too. So what's the difference? Is it that in approach 1, an instance is made to join as follower while in approach 3, it is not?

**Comment by obockows** [comment]
@agargi 
In 1st you have always quorum and that one you revert could have an outdated log (but for sure doesn't have the latest), so that's why it's safe. 

In 3rd approach you could overwrite the latest status (= lost some data)

EXAMPLE:
Master1, master2, master3 (leader). In logs we have the last “entry” written in term 1, index 11. Shutdown master1, disk snapshot, start back.  Changes, a new entry is written in term 1, index 12, committed. Shutdown master2, snapshot, start it back. Changes, a new entry is written again, still, term 1, index 13, shutdown master3, snapshot, start it back. Other activities, a failure, power off all, restore from disk snapshots and if we start master3 with master1 or master2, that’s ok. We have term2, RPC RequestVote from master1/master2 will be denied by master3 (due to “election restriction”). In the case of RequestVote from master3 it will be accepted and we have the quorum. 

If we start master1 and master2 first, master2 will be elected as leader, they have a quorum, master3 joins and its log should be overwritten, or even there will be some failure. It could be even more problematic if the scenario had been different, e.g. master3 comes with a higher RAFT Term (due to some changes between snapshots), the “In Search of an Understandable  Consensus Algorithm” doc doesn’t consider such unusual circumstances even.

**Comment by obockows** [comment]
@agargi unnecessary I pasted my previous description and the example. 
So let me stress out the difference:
In 1st case, you shut down and potentially revert just one snapshot at a time, that reverted member will be always in the role of follower and never has newer state then the other two. 
In 3rd case, you create 3 different snapshots and when you revert all of them you have the cluster state with anomalous state, e.g. master3 has written changes but the other 2 don't have it. Normally in the case of 3 members, it's not possible to write something if 2 out of 3 aren't written changes in their logs.
