### ISSUE TITLE
a client can cause a nil dereference in etcd by passing an invalid SortTarget

### ISSUE THREAD

**Issue by rtmrtmrtmrtm** [etcd-io/etcd#13554]
This code in Range() in server/etcdserver/apply.go leaves sorter = nil
if r.SortTarget has an unexpected value, leading to a page fault in
sort.Sort().

		var sorter sort.Interface
		switch {
		case r.SortTarget == pb.RangeRequest_KEY:
			sorter = &kvSortByKey{&kvSort{rr.KVs}}
		case r.SortTarget == pb.RangeRequest_VERSION:
			sorter = &kvSortByVersion{&kvSort{rr.KVs}}
		case r.SortTarget == pb.RangeRequest_CREATE:
			sorter = &kvSortByCreate{&kvSort{rr.KVs}}
		case r.SortTarget == pb.RangeRequest_MOD:
			sorter = &kvSortByMod{&kvSort{rr.KVs}}
		case r.SortTarget == pb.RangeRequest_VALUE:
			sorter = &kvSortByValue{&kvSort{rr.KVs}}
		}
		switch {
		case sortOrder == pb.RangeRequest_ASCEND:
			sort.Sort(sorter)
		case sortOrder == pb.RangeRequest_DESCEND:
			sort.Sort(sort.Reverse(sorter))
		}

I've attached a demo program and the resulting etcd output.

csh# etcd/bin/etcd --version
running etcd on unsupported architecture "riscv64" since ETCD_UNSUPPORTED_ARCH is set
etcd Version: 3.5.1
Git SHA: d42e8589e
Go Version: go1.16.2
Go OS/Arch: linux/riscv64

[etcd_4.c.txt](https://github.com/etcd-io/etcd/files/7765025/etcd_4.c.txt)
[etcd_4.out.txt](https://github.com/etcd-io/etcd/files/7765030/etcd_4.out.txt)

**Comment by ahrtr** [comment]
This issue will never happen if an application uses the etcd clientv3. 

Anyway, I just submitted a PR to add some protection code.

**Comment by serathius** [comment]
This is fix in apply, have we checked if API will accept sort=nil?

**Comment by ahrtr** [comment]
> This is fix in apply, have we checked if API will accept sort=nil?

Yes, the API accepts sort == nil. When the sort is nil, then both [SortOrder](https://github.com/etcd-io/etcd/blob/main/api/etcdserverpb/rpc.pb.go#L368) and [SortTarget](https://github.com/etcd-io/etcd/blob/main/api/etcdserverpb/rpc.pb.go#L370) will be 0. Please see [op.go#L39](https://github.com/etcd-io/etcd/blob/main/client/v3/op.go#L39) and [op.go#L165](https://github.com/etcd-io/etcd/blob/main/client/v3/op.go#L165).

The problem here is that the user doesn't use the clientv3 at all. Instead the example just sends the data to etcdserver via tcp connection directly. We do not have clientv3 of other programming languages either.

**Comment by serathius** [comment]
Protecting consistency by panic in apply should be also accompanied by added validation in API. If not this could cause security issue where client can take down server by sending invalid request that causes panic when applying change.

**Comment by ahrtr** [comment]
> Protecting consistency by panic in apply should be also accompanied by added validation in API. If not this could cause security issue where client can take down server by sending invalid request that causes panic when applying change.

Makes sense. Updated the PR.
