### ISSUE TITLE
Can an offline etcd instance join back an etcd cluster automatically

### ISSUE THREAD

**Issue by geotransformer** [etcd-io/etcd#13800]
### What happened?

One etcd instance was down (e.g., host power off, pod scale in, network partition, etc)

1> Can it join back the cluster directly? 

2> Is it required to cleanup the existing data before etcd instance joining back?

3> If it can join back cluster automatically, how long the offline is acceptable when an etcd instance is joining back?

### What did you expect to happen?

Offline etcd pod can join back automatically

### How can we reproduce it (as minimally and precisely as possible)?

Three node etcd cluster in Kubernetes. Scale in one pod and scale it out after a minute/hour/day/week

### Etcd version (please run commands below)

etcd 3.4 and 3.5

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
The short answer is YES, and no need to cleanup the existing data. 

> If it can join back cluster automatically, how long the offline is acceptable when an etcd instance is joining back?

I don't think there is any limitation here. 

The only comment is that you can't join an old member again if you recreate the cluster and reuse some peer addresses. Otherwise you will run into [cluster ID mismatch](https://github.com/ahrtr/etcd-issues/blob/master/docs/cluster_id_mismatch.md) issue.

**Comment by xiaods** [comment]
yes, it support it.
