### ISSUE TITLE
Verification of exchanged etcd snapshots

### ISSUE THREAD

**Issue by ptabor** [etcd-io/etcd#13973]
We observed following test flakes: 

Test failure - flake (https://github.com/etcd-io/etcd/runs/6091231156?check_suite_focus=true):

```
    logger.go:130: 2022-04-20T08:11:00.714Z	FATAL	m0	Verification failed	{"member": "m0", "data-dir": "/tmp/TestV3WatchRestoreSnapshotUnsync501892535/002/etcd4044943490", "error": "backend.ConsistentIndex (24) must be >= last snapshot index (25)"}
```

Discussion: https://github.com/etcd-io/etcd/pull/13942#issuecomment-1103833733

What happens is that a lagging follower is downloading a snapshot from leader. 
The snapshot is marked as representing exact 'wal-index' (i.e. snapshot-index). But within the snapshot file, the cindex < snapshot-index. 

We should: 
  - understand in what situation a generated snapshot (that is produced within Apply goroutine) is not reflecting the most recent cindex and fix. 
  - Add a verification (at least in tests, i.e. ETCD_VERIFY='snapshots') that:
      - the snapshot being produced has consistent cindex with it's expected WAL-log position
      - the snapshot being received matches the expectations

**Comment by ahrtr** [comment]
The issue was caused by the intermediate change (see below) in PR [13942](https://github.com/etcd-io/etcd/pull/13942).  

[server.go#L1823](https://github.com/etcd-io/etcd/blob/e02ac59cfc4e750f4b0a2a121e20db8e6775d5cd/server/etcdserver/server.go#L1823)

```
if  ar != nil  // This is not correct!!!
```

I believe we should be good with the final change in above PR,

```
if !applyV3Performed || (ar != nil && ar.err != nil) 
```

I agree that we should add a snapshot verification when a follower receive a snapshot.
