### ISSUE TITLE
contrib/lock: Doubtful about the example of distributed locks.

### ISSUE THREAD

**Issue by SimFG** [etcd-io/etcd#14224]
### What happened?

1. There is an error in the description of the `contrib/lock/README.md`  file.
detail: https://github.com/etcd-io/etcd/tree/main/contrib/lock
![image](https://user-images.githubusercontent.com/21985684/178985875-3f51c0a9-b58d-404d-b3ee-71d14cc42701.png)
The `client2` can't acquire the lock, because the lock has been acquired by the `client1`. And this is the same result when testing locally.
2. Why do version verification in the `storage` server?
If doing this, from the second time on, running the `client.go` will definitely report an error. Because the values of `session.Lease()` are different.
https://github.com/etcd-io/etcd/blob/73c714bf3d16e77d30175d8e27682190006e50fa/contrib/lock/storage/storage.go#L79-L92 

### What did you expect to happen?

Maybe I need more details about these code.

### How can we reproduce it (as minimally and precisely as possible)?

Running the `contrib/lock/storage/storage.go` and `contrib/lock/storage/client.go` files.

### Etcd version (please run commands below)

the main branch

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by tjungblu** [comment]
Hi @SimFG,

I'm not the original author, but I'm a sucker for distributed locking so I wanted to give this a bash. Maybe @chalin has some time to look into this eventually?

> The client2 can't acquire the lock, because the lock has been acquired by the client1. And this is the same result when testing locally.

Yep, I think that's not working anymore. I reckon that the gogc has changed significantly over time and it's not as easy to "stop the world" anymore. In fact, running `GODEBUG=gcstoptheworld=2 ./client 1` does panic for me in 1.18.2. 

Either way, you could manually revoke the lease on client 1 using `etcdctl lease revoke` and it would work as advertised.

> Why do version verification in the storage server?
> If doing this, from the second time on, running the client.go will definitely report an error. Because the values of session.Lease() are different.

As far as I can read the code, you have to restart the server as it will keep the leases under the same key `key0` and thus run into issues in subsequent runs. 

Within one run however, only client 2 should win the write with its lease id, which is why client 1 will receive the entirely expected error on writing the same key under a different lease id. This just tests that client 1 will not be able to successfully write with an expired lease. Maybe you're more familiar with this under the name of an optimistic concurrency etag write, which is usually handled server side.

**Comment by SimFG** [comment]
Thanks your answer. Maybe this part need to improve. When I firstly read it, I am very confused. I want to change it, but I don't know what this part of the code is trying to show.

**Comment by chalin** [comment]
Hi all. I'm not able to make such doc contributions at the moment. If there is a real issue here, consider leaving this open @SimFG. Thanks.

**Comment by SimFG** [comment]
@chalin Has opened.

**Comment by tjungblu** [comment]
gave this a bash in https://github.com/etcd-io/etcd/pull/14261, let me know if you need any adjustments in the code review

**Comment by SimFG** [comment]
> gave this a bash in #14261, let me know if you need any adjustments in the code review

I think it's pretty good !!!
