### ISSUE TITLE
Proposal for "Mentorship" for new contributors 

### ISSUE THREAD

**Issue by Elbehery** [etcd-io/etcd#14243]
This issue is to track a proposal to the etcd community, regarding a Mentorship program to the new etcd contributors. 
I have discussed with @ahrtr , and he has advised me to open this issue. 

The proposed program would assign new etcd contributors to a mentor who is experienced with the code base and can guide the mentee during his initial contributions.

I am very looking forward to the community addition to enhance the proposal 🙏🏽

**Comment by ahrtr** [comment]
Actually there are lots of online documents or videos on etcd, such as,
* [https://github.com/ahrtr/etcd-issues/blob/master/docs/cncf_storage_tag_etcd.md](https://github.com/ahrtr/etcd-issues/blob/master/docs/cncf_storage_tag_etcd.md) 
* [https://www.youtube.com/watch?v=H3XaSF6wF7w&t=214s ](https://www.youtube.com/watch?v=H3XaSF6wF7w&t=214s )

Anyone is welcome to contribute to the etcd project, and new contributors are recommended to get started with `good first issue`. We (maintainers, reviewers and other experienced contributors) will provide comments and helps on each issue/PR.

**Comment by ahrtr** [comment]
cc @spzala @serathius @ptabor

**Comment by serathius** [comment]
I think that having a dedicated mentor for new contributor is unrealistic due to size of community. As @ahrtr mentioned we already have materials and issues tagged for new contributors. It's maybe not obvious for people without prior experience in contributing for CNCF repos like K8s. Still if new contributors should be able to volunteer on opened issues and get all the support needed.

One area we could improve is having a more guided experience for new contributors. Resources and materials about contributing are very spread out and not easy to find. I would propose to add a section for new contributors in https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md that will list all available materials and where to find issues.

**Comment by parispittman** [comment]
this is related to my message here: https://lists.cncf.io/g/cncf-toc/message/7257 
does this resonate with etcd maintainers? I think y'all need a community function within the project to help get the burden of onboarding off of you. part of the community engineers job could be to figure out what mentoring looks like for etcd and establish programs.

**Comment by Elbehery** [comment]
+1

**Comment by lavacat** [comment]
"Mentorship" program can be a lot of work and if it's 1:1 then it's hard to scale/reuse.

Maybe we can start with this item from @parispittman list https://lists.cncf.io/g/cncf-toc/message/7257

> ama sessions for new contributors and those interested in maintaining
alternative name "New contributor onboarding".

- We can have it 2 weeks after regular community meeting and we can cycle timezones, so it's convenient.
- Maybe don't record this one, so it's more relaxed, only keep notes.
- Anybody can run this meeting, doesn't have to be a contributor. If there are some complicated questions they can be deferred to main community meeting.
- Additional topics for this meeting can be - "Intros",  "Discuss `help wanted` issues", "If folks tried working on the issue - what worked/didn't work", "go through a list of new/updated `help wanted` issues since last meeting"

This seams a low effort, potentially high impact and if there is no interest for 3 month or so, we can cancel it.

**Comment by Elbehery** [comment]
+1, that sounds great 👍

**Comment by serathius** [comment]
I have updated https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md. Proposal for mentorship is interesting but didn't get enough interest. Feel free to reopen when it gets enough traction (at least couple of people willing to offer their time to regularly join the program).

**Comment by Elbehery** [comment]
> I have updated https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md. Proposal for mentorship is interesting but didn't get enough interest. Feel free to reopen when it gets enough traction (at least couple of people willing to offer their time to regularly join the program).

Thanks a lot @serathius. appreciate ur response here and on slack 👍🏽 🙏🏽
