### ISSUE TITLE
etcd/raft go.mod polluted with test only dependencies

### ISSUE THREAD

**Issue by dims** [etcd-io/etcd#14513]
see graph below on how things like `cockroachdb/datadriven` etc end up in kubernetes via etcd dependencies. Even though we have a go.mod file under `raft` directory, since there is a intermix of code and tests, the go.mod file ends up with things it should not. Is it possible to move test only code to a separate directory and drop a new go.mod file there?

![image](https://user-images.githubusercontent.com/23304/192025017-6e2ae544-a0b4-437b-87af-980122f17911.png)

**Comment by serathius** [comment]
What kind of test dependencies do you care the most? I don't know if it's possible to just move all unit tests to separate package or remove dependencies from all unit tests. In the graph dependencies also go etcd/server package. Is it problematic for you too?

Overall note. This doesn't seem like etcd only issue, but a language issue. Test dependencies not being separated from the module. I don't know if issue can be fixes for every K8s dependency.

**Comment by dims** [comment]
@serathius for this specific ask, if we can introduce a go.mod in https://github.com/etcd-io/etcd/tree/main/raft/rafttest that will cut out a whole lot of stuff.

NOTE: if someone wants to use raft, they don't really want cockroachdb to go with it. yes, i agree it is a language issue, i am asking for the integration test dependencies not present in the library's go.mod file here. 

thanks!

**Comment by serathius** [comment]
@tbg thoughts?

**Comment by tbg** [comment]
`datadriven` is a small testing dependency (like `require`, for example). It's not ideal that it is in the import graph, as @serathius points out this is because of the `rafttest` package. I think the solution would be more simply to move the contents of `rafttest` (or at least `InteractionEnv`) into `_test.go` files in the raft package itself, as it's only used from within the raft tests. The original idea was to make it available to implementers as well, to check their implementations for correctness, but we can revisit that if that work actually happens.

By the way, I also have a pet peeve about dependencies, there is a dependency on `etcd/api/v3/versionpb`[^1] which has caused problems using the library from CockroachDB[^2]; effectively we're vendoring with a custom patch[^3]. I suspect this causes problems for other folks as well, so hopefully we can fix that too. Can etcd folks find a way to do their versioning in a way that doesn't require these field annotations and associated import?

[^2]: https://github.com/cockroachdb/cockroach/pull/88985#issuecomment-1261868315
[^3]: https://github.com/cockroachdb/cockroach/pull/89632/files#diff-02d48d3077b4114ffb5927c6a9cf38c8de98b25f4836144c304198f1c38f8f86

**Comment by tbg** [comment]
See also https://github.com/etcd-io/etcd/pull/14674#discussion_r1012809118. The `datadriven` dependency is pruned, so it's not actually pulled in when using the library.

However, `etcd/api/v3/versionpb` *is* a true dependency, i.e. a real problem:

```
$ go list -deps | grep etcd | grep -v raft
go.etcd.io/etcd/api/v3/versionpb
```

**Comment by ahrtr** [comment]
> By the way, I also have a pet peeve about dependencies, there is a dependency on `etcd/api/v3/versionpb`[1](#user-content-fn-1-570d84bd9f522f764b974511d9c889bc) which has caused problems using the library from CockroachDB[2](#user-content-fn-2-570d84bd9f522f764b974511d9c889bc);

Somehow I did not reproduce the issue locally.
```
$ go get go.etcd.io/etcd/raft/v3@d379e6221e10c32d83dc72ce39e0b19b3f00366f
go: downloading go.etcd.io/etcd/raft/v3 v3.6.0-alpha.0.0.20220928120404-d379e6221e10
go: downgraded go.etcd.io/etcd/raft/v3 v3.6.0-alpha.0.0.20221022111340-aac5feec94a9 => v3.6.0-alpha.0.0.20220928120404-d379e6221e10
```

**Comment by ahrtr** [comment]
Note that this isn't an issue for etcd `main` (3.6), please see https://github.com/etcd-io/etcd/pull/14674#discussion_r1013718338

**Comment by serathius** [comment]
Based on comments above I conclude that issue is no longer affecting etcd main as it addopts go1.17 which introduced [module graph pruning](https://go.dev/ref/mod#graph-pruning). Downstream users of raft library are no longer affected by test dependencies used by raft, so there is no need to follow this up.

@dims @liggitt is this ok with you? Can we close the issue?

**Comment by tbg** [comment]
@serathius I'm happy to file a new issue for this as well, but the above question[^q] still stands and seems pertinent as it has caused a number of problems at least for CRDB's import of raft:

By the way, I also have a pet peeve about dependencies, there is a dependency on `etcd/api/v3/versionpb`[^1] which has caused problems using the library from CockroachDB[^2]; effectively we're vendoring with a custom patch[^3]. I suspect this causes problems for other folks as well, so hopefully we can fix that too. Can etcd folks find a way to do their versioning in a way that doesn't require these field annotations and associated import?

[^1]: https://github.com/etcd-io/etcd/blob/1b4e54c238114b77448daf8f9375c2da9f969f88/raft/raftpb/raft.pb.go#L14
[^2]: https://github.com/cockroachdb/cockroach/pull/88985#issuecomment-1261868315
[^3]: https://github.com/cockroachdb/cockroach/pull/89632/files#diff-02d48d3077b4114ffb5927c6a9cf38c8de98b25f4836144c304198f1c38f8f86


[^q]: https://github.com/etcd-io/etcd/issues/14513#issuecomment-1301980348

**Comment by serathius** [comment]
Me and @ahrtr cleanup all raft dependencies on etcd in https://github.com/etcd-io/etcd/pull/14705 and https://github.com/etcd-io/etcd/pull/14703

@tbg Can you work on removing dependency on `github.com/cockroachdb/datadriven` ?

**Comment by tbg** [comment]
@serathius we don't want to remove the dependency (recall that this is a little testing library that we use prominently in raft), all we can do is move it explicitly into testing-only code. But either way, users of the library don't pick it up due to pruning.
