### ISSUE TITLE
allow reads from learner / non-voting read-only members

### ISSUE THREAD

**Issue by gpl** [etcd-io/etcd#14994]
### What would you like to be added?

I'd like a way to have a non-voting etcd member that I can read from as a client.  I saw that as part of the `learner` work; reading as client is explicitly rejected/disabled.

### Why is this needed?

In cases where we can tolerate stale data but need higher performance, we'd like to be able to linearly scale reads.

**Comment by gpl** [comment]
unstale

**Comment by serathius** [comment]
I think the problem is that overall architecture based on the current implementation of learners would not scale. Learners get updates from leader. Previous maintainers were even scared about multiple learners being able to overload leader. 

I think what you want is more eventually consistent proxy, like etcd-proxy.
