### ISSUE TITLE
pkg/v3/ioutil TestPageWriterRandom is flaking

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [etcd-io/etcd#16255]
### Which github workflows are flaking?

Jobs in our internal CI are flaking

### Which tests are flaking?

pkg/v3/ioutil TestPageWriterRandom

### Reason for failure (if possible)

The test is failing https://github.com/etcd-io/etcd/blob/main/pkg/ioutil/pagewriter_test.go#L43

We initially noticed it in `ppc64le` architecture that our CI jobs use.
Later when verified, this test is failing even on **x86_64**
```
[root@toad1 etcd]# go test -v go.etcd.io/etcd/pkg/v3/ioutil -c -count=1
go: downloading github.com/stretchr/testify v1.8.4
go: downloading go.uber.org/zap v1.24.0
go: downloading golang.org/x/sys v0.10.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading go.uber.org/atomic v1.7.0
go: downloading go.uber.org/multierr v1.11.0
[root@toad1 etcd]# ./ioutil.test -test.run TestPageWriterRandom
PASS
[root@toad1 etcd]# ./ioutil.test -test.run TestPageWriterRandom
PASS
[root@toad1 etcd]# ./ioutil.test -test.run TestPageWriterRandom
PASS
[root@toad1 etcd]# ./ioutil.test -test.run TestPageWriterRandom
--- FAIL: TestPageWriterRandom (0.00s)
    pagewriter_test.go:43: got 5016 bytes pending, expected less than 128 bytes
FAIL
[root@toad1 etcd]# ./ioutil.test -test.run TestPageWriterRandom
PASS
[root@toad1 etcd]# ./ioutil.test -test.run TestPageWriterRandom
PASS
[root@toad1 etcd]# uname -a
Linux toad1.fyre.ibm.com 4.18.0-358.el8.x86_64 #1 SMP Mon Jan 10 13:11:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@toad1 etcd]# go version
go version go1.20.6 linux/amd64
[root@toad1 etcd]#
```

### Anything else we need to know?

Also flaking in `ppc64le` architecture:
```
[root@raji-workspace etcd]# ./ioutil.test -test.run TestPageWriterRandom
PASS
[root@raji-workspace etcd]# ./ioutil.test -test.run TestPageWriterRandom
PASS
[root@raji-workspace etcd]# ./ioutil.test -test.run TestPageWriterRandom
--- FAIL: TestPageWriterRandom (0.00s)
    pagewriter_test.go:43: got 3325 bytes pending, expected less than 128 bytes
FAIL
[root@raji-workspace etcd]# ./ioutil.test -test.run TestPageWriterRandom
PASS
[root@raji-workspace etcd]# uname -a
Linux raji-workspace.power-iaas.cloud.ibm.com 4.18.0-496.el8.ppc64le #1 SMP Mon Jun 5 15:04:52 UTC 2023 ppc64le ppc64le ppc64le GNU/Linux
[root@raji-workspace ~]# go version
go version go1.20.6 linux/ppc64le
[root@raji-workspace ~]#
```

**Comment by Rajalakshmi-Girish** [comment]
@ping40 @ahrtr any thoughts on this, please?

**Comment by fuweid** [comment]
If my understanding is correct, the test code is not correct.

https://github.com/etcd-io/etcd/blob/e209968dc325a3b6250eb5eb8be3229c8d2c7e23/pkg/ioutil/pagewriter_test.go#L42

The page writer has cache buf for pending write. The buf size is `pageBytes+defaultBufferBytes`. Since the bytes is random, after 4096 rounds, there are pending bytes in the cache. So I think the L42 should be changed to `if n-cw.writeBytes > pageBytes+defaultBufferBytes {`.


https://github.com/etcd-io/etcd/blob/e209968dc325a3b6250eb5eb8be3229c8d2c7e23/pkg/ioutil/pagewriter.go#L56-L80

**Comment by Rajalakshmi-Girish** [comment]
> pageBytes+defaultBufferBytes

Your suggested change fixed the issue.

```
[root@toad1 etcd]# go test -v go.etcd.io/etcd/pkg/v3/ioutil -c -count=1
[root@toad1 etcd]# /root/go/bin/stress ./ioutil.test -test.run TestPageWriterRandom
5s: 2165 runs so far, 0 failures
10s: 4432 runs so far, 0 failures
^C
[root@toad1 etcd]# cat pkg/ioutil/pagewriter_test.go | grep "n-cw.writeBytes >"
        if n-cw.writeBytes > pageBytes+defaultBufferBytes {
[root@toad1 etcd]#
```

**Comment by ahrtr** [comment]
The PR https://github.com/etcd-io/etcd/pull/16268 looks good to me. 

But I realized that the `NewPageWriter` implementation has a performance issue. When writing a large amount of data, it actually writes the data page by page, no matter what's the buffer size. Let's work with an example.

Assuming
```
defaultBufferBytes = 4094 (4K)
pageByte: 1024 (1K)
pageOffset: 0
```

When writing 9K data, the expected behaviour is writing twice, each with 4K data, and the left 1K data is cached in the buffer. But actually it writes 5 times, each with 1K (the pageSize) data, and left 4K data is cached in the buffer.

**Comment by fuweid** [comment]
https://github.com/etcd-io/etcd/blob/35628b9c7859d4f68f539dadc704b80c9529f7b1/pkg/ioutil/pagewriter.go#L86-L94

According to the code, when writing 9K data, since 9K = 9 * pageByte, the code will write all the data once. No pending bytes in cache.
