### ISSUE TITLE
Hook up etcd to kubernetes' prow infrastructure to run CI jobs

### ISSUE THREAD

**Issue by dims** [etcd-io/etcd#16653]
To be able to run for example the robustness suite regularly?
- https://github.com/etcd-io/etcd/tree/main/tests/robustness
- https://github.com/etcd-io/etcd/tree/main/tools/rw-heatmaps

**Comment by dims** [comment]
cc @chaochn47

**Comment by chaochn47** [comment]
Related to https://github.com/etcd-io/etcd/issues/16467 and please check https://github.com/etcd-io/etcd/issues/16467#issuecomment-1691326907. @jmhbnz, who is the expert in this area. 

/cc @mehvaibh since you are interested based on https://github.com/etcd-io/etcd/issues/16510#issuecomment-1708961798. 

> To be able to run for example the robustness suite regularly?

    https://github.com/etcd-io/etcd/tree/main/tests/robustness
    https://github.com/etcd-io/etcd/tree/main/tools/rw-heatmaps

Those are already run regularly in upstream, problem is we don't have public SLO/SLAs that can be a baseline to compare with. No visualization of the trend. 

I am keen to close this issue and register to https://github.com/etcd-io/etcd/issues/16467. WDYT?

**Comment by jmhbnz** [comment]
Hi @dims - Many thanks for raising this. I think this directly relates to our overall `sig-etcd` efforts and direction. We should probably flesh it out in our checklist here: https://docs.google.com/document/d/1JGpsDlQui6UcOnARk3Hvq-kYpWWmSQZTvs7FGXhYKdA/edit?resourcekey=0-ip9ms08vN1JsOnZdPGJL_g#heading=h.v3ryuqty15x4

I would be happy for https://github.com/etcd-io/etcd/issues/16467 to be an early candidate for prow workloads for etcd. Perhaps in an iterative manner as each individual SLI is agreed and put together.

Thanks for getting the ball rolling with github admins, I am happy for this issue to stay open to track the actual mechanics of getting kubernetes prow infra setup / enabled for the etcd-io github org.  Once enabled we can use other issues to track adding specific jobs etc.

Note - This is a direct enabler for:
- https://github.com/etcd-io/etcd/issues/15659

**Comment by jmhbnz** [comment]
Closing - Prow is now hooked up for etcd-io/etcd, refer dashboard https://prow.k8s.io/?repo=etcd-io%2Fetcd. There is further work in progress being discussed under https://github.com/kubernetes/k8s.io/issues/6102.
