### ISSUE TITLE
`(*batchTx) UnsafeDelete` may break the linearizability

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#17158]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

## TL; DR
`(*batchTx) UnsafeDelete` may break the linearizability. etcd may still read stale data when during applying a request if previous applying process includes `(*batchTx) UnsafeDelete` request(s).

## Root cause
Please refer to
- https://github.com/etcd-io/etcd/pull/17157
- https://github.com/etcd-io/etcd/pull/17119#issuecomment-1857547158
- Test case `TestRangeAfterDeleteMatch` in https://github.com/etcd-io/etcd/pull/17124

## Solution
The PR should contains the following content/commits,
- Add a couple of new test case on removing users/roles to reproduce the issue
  - Let's use the auth users as an example. Firstly add an user, then remove it and immediately after add it again. The client may get an `ErrUserAlreadyExist` error.
- Cherry-pick the test case `TestRangeAfterDeleteMatch` in https://github.com/etcd-io/etcd/pull/17124;
- Cherry-pick https://github.com/etcd-io/etcd/pull/17157: (it is the simplest solution I can think of). Confirm that it can fix the test failures
  - Please fix the test failures
- Please feel free to suggest any other test case

## Backport
The fix should be backported to both 3.5 and. 3.4

### What did you expect to happen?

Ensure linearizability on any deletion operations.

### How can we reproduce it (as minimally and precisely as possible)?

See above

### Etcd version (please run commands below)

<details>
all releases

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
We are seeing more and more compounding issues with `batchTxBuffered`, I think we should consider two things:
* More generic testing like proposed in https://github.com/etcd-io/etcd/issues/17126, there is just too much risk of missing an issue due to how complicated the code is. 
* Better impact analysis. We know that txn correctness issues don't affect KV store or they would be found by robustness tests. However there is large API surfaced not covered by robustness tests. Things like authorization, membership, leases etc. I think we need to add a verifier that will confirm correct behavior of backend.  See https://github.com/etcd-io/etcd/blob/main/server/verify/verify.go#L46 as an example

**Comment by ahrtr** [comment]
Resolved
