### ISSUE TITLE
How to implement master election on top of test-and-set?

### ISSUE THREAD

**Issue by shamrin** [etcd-io/etcd#225]
I've got a question in reaction to @philips [HN comment](https://news.ycombinator.com/item?id=6531735):

> You build master election on top of the test and set functionality of etcd which gives you a cluster wide locking mechanism. The plan is to provide a simplified master election REST api as a module, just like the dashboard in this release is a module.
> 
> But, nothing is stopping a regular etcd client from building master election on top of the current API.

Could you please give some pointers on how to implement master election on top of test-and-set? What is the algorithm? I've tried searching for it, but couldn't find it. Probably missed the right keywords.

**Comment by duffqiu** [comment]
from 2.0, there is no interface for master election, how shall I do for such propose?

**Comment by yichengq** [comment]
Reimplementation of the module is on the TODO list. If you want to do for such propose now, you may need to follow the ZK pattern and write your own.

**Comment by purpleidea** [comment]
This implementation: https://github.com/datawisesystems/etcd-lock seems to have rotted, and I haven't looked at fixing this yet. Is there a recommended way to do this?

More to the point, I thought that the raft protocol elects a leader, is there some way to expose this so that a client can tell which peer is the elected master?

Thanks!

**Comment by yuzhichang** [comment]
FYI, in etcd 3.0+, "etcdctl elect" is the sample code for election campaign and observe. See https://github.com/coreos/etcd/blob/master/etcdctl/README.md for document.
