### ISSUE TITLE
etcdserver, etcdctl: archiving compaction

### ISSUE THREAD

**Issue by heyitsanthony** [etcd-io/etcd#5128]
etcd currently offers two options for compaction policy: a time-based automatic compaction policy and user-invoked compactions. In cases where total history archival is important, neither of these policies are totally adequate; both auto compaction and user-invoked compaction drop history on the floor without extra off-path commands (e.g., backup or mirror) to save history. Backup / mirror-maker seems insufficient for this case because the compaction wouldn't be guarded by backup/mirroring-- if the backup or mirror fails the compaction won't know about it and will cheerfully cause data loss.

Ideally, there would be a way to better tie archiving with compaction so that there's less risk of nuking important history.

**Comment by pjz** [comment]
Another option would be to add a 'nearline' option - with the understanding that retrieval would be slower than the 'online' set, allow all of history to be moved to disk-based storage.  Existing APIs would work for access, perhaps with a 'allow nearline search' flag that has to be set to allow the (potentially slow) searching of history that's been compacted to nearline storage, in order to prevent users from being surprised if their search ends up being slow.

**Comment by pjz** [comment]
Still desired... maybe feature requests should be exempt from being marked stale?
