### ISSUE TITLE
raft: improve the availability related to member change

### ISSUE THREAD

**Issue by hhkbp2** [etcd-io/etcd#7625]
Hi,

Current member change implementation requires at least two nodes works for a cluster. If one node fails in a three nodes cluster, there is a short time gap that the availability risks on another node failure, after the previously failed node is removed, before the new node is added.

Another availability issue arises when balancing the nodes among racks/data centers. It's an usual way to add a new node and then remove one old node among different racks/data centers to do the balancing.  After adding a node into a three nodes cluster in one of the three racks/data centers, there will two nodes in one same rack/data center. If this rack/data center fails, the cluster is unavailable. The elaboration for this issue is in https://github.com/pingcap/tikv/issues/1468 

Both availability issues are related to the member change implementation. To fix them, I suggest to add a "ReplaceNode" primitive in member change. It requires to write and then commit one log entry to achieve the target "remove one existing node and add a new node".

**Comment by heyitsanthony** [comment]
I don't understand what the atomicity buys over remove/add?

For the first case, if the node failed, then removing it from membership doesn't seem to make the fault tolerance worse-- the cluster will lose availability if another node fails regardless. The window is slightly shorter with ReplaceNode since there's only one a commit instead of two, but window is still there.

The rack case is more convincing, but I'm not sure if there's an advantage over remove/add at the moment. There's still the risk that the replacement node will be misconfigured and will fail to join with raft, so it loses add/remove's advantage that ensures the new node is participating in raft before shutting off the old node. There would have to be non-voting member support before ReplaceNode can be safe.

**Comment by siddontang** [comment]
Hi @heyitsanthony 

For TiKV or Cockroachdb, which needs to schedule multi raft groups in different DCs, If one DC fails when scheduler is working (moving one replica from a host to another host in same DC), the corresponding raft group can not work unless DC is up again, regardless of whether using add + remove or remove + add. 

Of course, we can use 5 replicas to solve the problem in 3 DCs, but I think this may hurt the performance and is not necessary. A better way is to implement atomic Replace operation or joint consensus, both are mentioned in Raft Paper. Supporting joint consensus will change a lot codes in etcd raft, Replace may be more simple here.

**Comment by heyitsanthony** [comment]
@siddontang sure, I understand that. I'm asking if ReplaceNode will be effective enough at maintaining availability without non-voting member support. The new node could turn out to be incapable of participating in raft but there's no way of knowing until after it's added, so there's still a risk of going from 3 to 2. Non-voting would at least establish that the new node can contact the raft group and accept commits. Or is this not a problem?

ReplaceNode would be useful on its own provided the new node can be guaranteed to catch up with the cluster quickly (which is better than nothing, as it is now), just saying that it seems like it solves only half of it...

**Comment by hhkbp2** [comment]
@heyitsanthony Yeah, it needs some time to catch up with the leader for a blank new node which is just added into the cluster. And there's still a risk of node failure during this "ReplaceNode" procedure. A better way to perform the member change in this situation would be:

1. Initialize a non-voting node in the target rack/data center. Replicate snapshot/log to this non-voting node until it's close enough (until the log gap could be covered within one election timeout as described in Raft Thesis 4.2.1)  
2. Perform the "ReplaceNode" action to remove one node and add this prepared one

Each of 1, 2 could be implemented once at a time to solve the issue together. We could get 2 as the first step.

**Comment by xiang90** [comment]
@hhkbp2 @siddontang 

> Yeah, it needs some time to catch up with the leader for a blank new node which is just added into the cluster. 

There are cases where you can add a bad member (too slow to catch up, unreachable IP). I think @heyitsanthony feels those risks outperform the risk of allowing the small window between add/remove. If we really care about safety, we should fix the most significant problem first.

The right way to do the replacement is probably:

1. start non-voting member
2. non-voting member is sync
3. replace the old member with non-voting member

**Comment by heyitsanthony** [comment]
Starting with ReplaceNode seems fine... it's still one less way the cluster can break (even without non-voting) and it needs to be done anyway.

**Comment by xiang90** [comment]
no one is actively working on this. i am going to move it to unplanned.

**Comment by tbg** [comment]
The CockroachDB team is planning to implement joint consensus in the upcoming ~6 month release cycle (to commence shortly). An in-progress [RFC](https://github.com/cockroachdb/cockroach/pull/36098) is available.

Similar to what has been stated in this thread, an atomic "replace" primitive would be enough on our end as well, though unless this allows for some kind of simplification we will implement support for arbitrary membership changes.

The research done in the RFC so far suggests that the etcd approach of activating configuration changes only when nodes *apply* them is undesirable (if not outright unsound). The plan is thus to implement joint consensus as outlined in the Raft thesis, where a configuration change becomes active the moment it is appended to the log. Input on this decision is welcome. We're somewhat in the dark on why `etcd/raft` originally decided to deviate from the thesis. I traced this all the way back to https://github.com/etcd-io/etcd/pull/1100, but there's not much in terms of justifying that decision. It sort of seemed to just have happened.

The move to joint consensus presents a challenge for upgrades. For compatibility reasons, we need the version of `etcd/raft` that implements joint consensus to at least tolerate but likely also plan "regular" one-at-a-time membership (V1) changes. However, we're not planning to add full support for returning to V1 membership changes after a V2 membership change.

I'm curious what expectation maintainers here have regarding the interface `etcd/raft` exposes to the application. For example, are we free to modify the `Storage` interface to accommodate joint consensus? Taking into account the migration constraints we already have (see above) this means that applications which do not wish to use joint consensus can continue to not use it, though they will have to slightly adapt their interfaces (probably by wrapping their existing `Storage` into a `etcd/raft`-provided compatibility wrapper). If we are not allowed to "break" existing applications in this way, we'll provide a `StorageV2` interface which can be supplied via the `Config` and which, if specified, enables the use of V2 (joint consensus) replication changes, while at the same time continuing to support V1 (one-at-a-time changes).

Personally, I believe that asking users to slightly adapt their interfaces is fine, but I would like to have some clarity from the maintainers going forward.

cc @xiang90 @gyuho @yichengq

**Comment by jingyih** [comment]
@tbg Do you want to briefly talk about this in etcd community meeting? 
https://docs.google.com/document/d/16XEGyPBisZvmmoIHSZzv__LoyOeluC5a4x353CX0SIM/edit#heading=h.tu6uwzxqfg8x

**Comment by gyuho** [comment]
I remember @xiang90 had some discussion with @ongardie... Can't find the link.

**Comment by gyuho** [comment]
@xiang90 

This is the closest that I can find:

https://groups.google.com/d/msg/raft-dev/t4xj6dJTP6E/NMfCgTO90t0J

>  In etcd/raft implementation, we actually used a different but similar
approach. We only applied the configuration change after it is
committed by the old quorum (rather than as soon as it is added). I
thought this is more safe and the configuration change command would
go through the same commit/apply path as normal command.

**Comment by siddontang** [comment]
Interesting, @gyuho  @xiang90 

We have already supported joint consensus in the Rust raft-rs https://github.com/pingcap/raft-rs/pull/202, but have not used in TiKV yet. We can contribute back to etcd Raft.

**Comment by tbg** [comment]
Thanks @jingyih, I'll be there. Added an item the agenda.

**Comment by xiang90** [comment]
@tbg 

So some history here.

When we started to implement etcd/raft, we want to start with a simpler reconfiguration protocol (both to save time and to explore if it is actually feasible). As a result, etcd implemented the atomic membership change first, then Raft thesis published with a modified version of atomic membership change later on. The idea is similar, but they are not exactly the same. 

I like apply time reconfiguration since the reconfig command will involve both raft protocol change as well as the application level change. I want the application level change to be strictly ordered. To implement this with commit time reconfiguration, the code/execution path for raft protocol change and application level change  for reconfiguration have to be separated. From safety perspective, I remember we added a few barriers to avoid the double in flight reconfiguration. To be honest, I do not member the details now, and I am not sure if the cases described in your analysis can actually happen. If it can happen, I guess it is still fixable :P.

**Comment by xiang90** [comment]
I am fine with adding joint membership change as an alternative way. Do you really need to replace the atomic one or they can co-exist (at least some can config to use one or the other at start time)?

**Comment by tbg** [comment]
Thanks @xiang90. The both of us chatted about this in the [meeting](https://docs.google.com/document/d/16XEGyPBisZvmmoIHSZzv__LoyOeluC5a4x353CX0SIM/edit#) just now, but for posterity:

- I think the current `etcd/raft` membership change protocol is unsound (I'll post details and what I've tried to fix it later)
- We agree that the apply-time (`etcd/raft`) config changes are much easier to work with from an app perspective, and that switching to the Raft paper way (append-time) really complicates things. We'd like to avoid having to do that, which means finding a way to make apply-time safe
- Safe meaning provably safe, in a way that won't randomly break (i.e. based on some stable invariants). It won't be as nice as in the paper but as long as we get the confidence that's fine by me.

I'd like to exhaust the apply-time options first before considering implementing the Raft paper way (append-time) like raft-rs did (though it might come to that). @siddontang thanks for the pointer, it's good to see that the end result of the second option. Did you consider fixing up the apply-time protocol at all? Or even more fundamentally, what drove the decision to switch to append-time? Were you also concerned about the correctness of the current approach?

**Comment by tbg** [comment]
Here's one of the counter-examples I've been thinking of: https://gist.github.com/tbg/bac03e340532dd811ce16ff5c76725ba

In short, if followers help commit config changes but don't apply them, bad things can happen because "non-adjacent" config changes can be in use at the same time. Something is conceptually unsound there. Ideas that try to force peers to apply all outstanding entries before trying to use their config are hard to enforce because between paginated entry application as well as regressing commit and applied indexes, there seem to always be ways for peers to end up in places where they don't even *know* that they can apply the conf change they need to use before they've talked to other nodes which, well, they're not allowed to do under their old conf.

> From safety perspective, I remember we added a few barriers to avoid the double in flight reconfiguration.

The barrier that I know of is that no node will propose a conf change until all possible earlier conf changes have *applied*, but that's only locally. Other followers may not have applied the conf change at that point, and that leads to the counter-examples.

The best idea I had so far for avoiding this kind of problem is to actually force a quorum of followers to have *applied* the conf change as well. This requires tracking the applied index (and syncing the applied index whenever a conf change is applied so that it doesn't regress back past a conf change), but this kind of tracking seems kind of useful anyway for debugging or flow control, and it isn't too hard to introduce. However, I don't think it completely solves the problems:

- initial state: peers n1, n2, n3 with n2 leader
- n2 proposes membership change to add n4
- all peers receive it in the log and it commits, but n1 doesn't apply it
- n2 and n3 apply it, so it's applied on a quorum
- n2 adds n5, same game ensues (n2, n3, n4 apply it, n1 does not)
- n2 adds an entry to its log, replicates it to n1, but then steps down as leader (let's say a network partition {n1,n2} {n3,n4,n5} happens)
- n3, n4, n5 can elect a leader among themselves and make progress
- n1 is still using the config {n1,n2,n3} and it can get a vote from n2 to step up as leader

At the end of all this, if n1 does anything without first applying all outstanding entries, it causes split brain. To prevent this situation, somehow we need to force n1 to catch up on all of the config changes, ideally before even campaigning. However, the commit index can regress (it can only regress in certain ways in `etcd/raft` when the WAL and state machine share a storage medium, but I don't want to rely on intricate assumptions like that), so we may not be able to do so based on local knowledge.

Perhaps something like forcing a commit index to be persisted anytime a config change is marked as committed can help. I have to think about this more, but it feels like trying to salvage the unsalvageable.

**Comment by tbg** [comment]
Hmm, I do maybe have something that is reasonable. Let me sleep on it and if I still consider it reasonable tomorrow, I'll polish it up and post it here.

**Comment by jingyih** [comment]
I need more time to read and catch up. In the meantime, I do want to point out something at might be related to this discussion. In etcd, not all conf change entries are eventually "applied". It depends on some validation logic in etcd server:

https://github.com/etcd-io/etcd/blob/616592d9ba993e3fe9798eef581316016df98906/etcdserver/server.go#L2047-L2055

Depends on the output of `ValidateConfigurationChange()`, server either calls `Node.ApplyConfChange` to apply changes to local raft node, or calls the same function with nodeID set to zero to "not apply".

**Comment by tbg** [comment]
> In the meantime, I do want to point out something which might be related to this discussion

Thanks @jingyih. I had looked through the `etcdserver` code a few days ago and had noticed that too.

Things work differently in CockroachDB, there we emit the ConfChange in an entry that finalizes a configuration change transaction, and being in a transaction ensures that we'll only ever ask Raft to change membership in a way that makes sense (because the txn basically does a `CPut` on the existing config).

In both cases, things get trickier if we switch to the Raft paper approach, though it's still doable.

**Comment by tbg** [comment]
As promised, here's the write-up of how I think we might get away with apply-time after all. Don't be lulled into a wrong sense of safety by the fact that this looks properly typeset and all. I will only trust this when it's been independently verified.

# Saving apply time activation

I believe that the  invariants below result in an argument that shows
correctness of the apply-time approach. I also think that these invariants can
be achieved in a way that's stable to subsequent changes of the codebase.

I'll describe the invariants first, then a safety argument, then how we make the
invariants hold in code.

## Invariants

- (Apply): a leader will not append a config change to its logs when it hasn't
applied all previous config changes in its logs.
- (Campaign): a node will not campaign until it has applied any configuration
changes with indexes less than or equal to its committed index.
- (Append): appending a config change to the log (at leader or follower) implies
that any previous config changes are durably known to be committed. That is, a
commit index is persisted (and synced) that encompasses any earlier config
changes before a new config change is appended.

## Safety

First a bit of notation and reminders.

### Primer and notation

The quorums of a configuration C are sets of nodes that have the property that
they intersect pairwise, i.e. for two quorums Q and Q', the intersection is
nonempty.

Raft has two types of configurations: regular and joint configurations. A
regular configuration is simply a set of nodes whose quorums are the subsets
consisting of `(n div 2) + 1` members. A joint configuration between A and B has
as its set of nodes the union of those of A and B, and its quorums are exactly
the unions of a quorum of A and a quorum of B.

For example, a regular three-node config A for nodes `{1,2,3}` has quorums
`{1,2}`, `{2,3}`, `{1,3}`, and `{1,2,3}`.

The joint config between `A={1,2,3}` and `B={3,4,5}` has nodes `{1,2,3,4,5}` and
quorums `{1,2,3,4}`, `{1,2,3,5}`, `{1,2,4,5}`, `{1,3,4}`, `{1,3,5}`, `{2,3,4}`,
`{2,3,5}` (as well as the quorums with "extra members"). Note how the overlap
between A and B shrinks some of the resulting joint quorums.

Let A, B, ... be a sequence of configuration changes. Raft will only allow a
config change that is compatible with its predecessor, meaning that for any
quorum Q taken from A and P from B, Q and P have at least one node in common.

Regular configurations which differ by at most one node are compatible, and form
the basis of the simple (i.e. non-joint) Raft membership change protocol.

Additionally, for any configurations A and B, the joint configuration between A
and B is compatible with both A and B, though A and B are not necessarily
compatible.

### The argument

To prove safety of apply-time replication changes, we need to prove that if a
configuration change C with predecessors B and A is first activated by a node,
no node using A can win an election.

A configuration change activates at apply time, so we know C was committed,
which in turn applies that C was appended to a B-quorum of B-nodes. Thanks to
(Append), this implies that B is durably committed on all B-nodes that have C in
their logs, a set which is a quorum.

A node without C in its log is using either A or B to campaign (it may not even
have B). It can't win using either since any quorum of A or B contains at least
one node of the quorum of B that has C in their logs (because A and B are
compatible). But that node, and thus that quorum, would not elect the node
without C in the logs as leader.

Hence, in an event triggering any node to campaign, a candidate with any chance
of success necessarily has C in its logs, and has B durably committed. Thanks to
(Campaign), it will campaign using either B or C. We thus conclude that config A
is inactive.

## Implementing the invariants

We already have (Apply) in today's etcd/raft code. (Campaign) is not difficult
to implement, we can simply ignore the triggers when we need to (though we may
want to campaign once we are caught up to avoid delays in leadership transfers,
etc).

(Append) is the interesting one. On the leader, it is straightforward since the
commit index is available and is guaranteed above that of the previous config
change due to (Apply); we just need to make sure that when we append the new
entry, we also persist the known commit index durably.

Next, all that's left to do is to make sure that commit index is used for all
future MsgApp to followers that distribute this log index. This seems straight-
forward and should be true today already. Note that if a follower is behind
(perhaps by multiple config changes), it may receive the missing log entries in
chunks and won't learn the leader's actual commit index until it's fully caught
up to it, but each chunk preceding the leader's durably committed index will be
sent with a commit index encompassing the whole chunk. Similar to the leader,
whenever followers append a conf change entry to their log, they sync their
currently known commit index.

Snapshots are harmless if they don't include Raft log entries or, at least, no unapplied log entries.
If they do, they must come with a proper commit index which must be synced. For example, a
good strategy might be to send only the entries corresponding to the commit index. Snapshot application must be synced anyway, so the "durable" part should be free except in very exotic apps.

Applications are encouraged to not send log entries in the snapshots if they can avoid it, but sometimes it's necessary. For example, CockroachDB had to do it until recently for technical reasons (though we never had to send unapplied entries).

**Comment by purpleidea** [comment]
@tbg In case it's helpful, I've been working on dynamic membership changes in https://github.com/purpleidea/mgmt/

Code is here: https://github.com/purpleidea/mgmt/tree/master/etcd and is used inside of mgmt itself.

There are many ways it needs improvements because there are architectural changes inside of etcd that would make it easier and race free, but in case it's helpful, feel free to ping if you'd like to chat more about it. I think our goals overlap here.

Thanks!

**Comment by bdarnell** [comment]
> for any quorum Q taken from A and P from B, Q and P have at least one node in common.

Nit: "the intersection of Q and P is non-empty" for consistency with the language earlier. 

> Thanks to (Append), this implies that B is durably committed on all B-nodes that have C in
their logs, a set which is a quorum.

...a B-quorum (or "a quorum of B" and drop the only-used-once B-quorum notation)


Looks good to me.

**Comment by nvanbenschoten** [comment]
Looks good to me as well, although I think it would be useful to write a follow up to [your gist](https://gist.github.com/tbg/bac03e340532dd811ce16ff5c76725ba) which specifical contrasts the behavior before and after your proposed invariants.

Also, the invariants in your proposal are well factored, but I think it would be useful to make very explicit the lemmas (is that the right term? I'm not a mathematician) that can be derived from them. For instance:
L1. the (Append) invariant ensures that no replica may hold more than one uncommitted/implicitly committed config change in its log. The sync you require ensures that this is true even after a restart _[1]_.
L2. the (Campaign) invariant and the (L1) lemma combine to ensure that any candidate that has campaigned in a leader election must have at most one unapplied config change in its log (uncommitted or implicitly committed).
L3. the (Apply) invariant ensures that a leader will never propose a config change unless it is currently using a compatible config

_[1]_ this is assuming the Raft log append and the HardState update are atomic. `etcd/raft` [doesn't seem to require this](https://github.com/etcd-io/etcd/blame/886d30d223a0c97f214ac0902bc150d656cd4101/raft/README.md#L116).

**Comment by xiang90** [comment]
@tbg 

The problems is to avoid: 
1. commit time configuration brain split (leader constraints)
2. voting time configuration brain split (candidate constraints)

I thought we implemented both of the constraints in etcd/raft already :P. So I agree with your detailed analysis.

> a node will not campaign until it has applied any configuration
changes with indexes less than or equal to its committed index.

This should be straightforward.

I am not sure if we need the 3rd one as a requirement. For leader, Apply rule already implies it. 

For followers, a new config change will be sent from leader with commit index inside AppMsg. The commit index of the AppMsg that contains the newest config change must be greater than the index of the previous config change (by Apply rule).

@nvanbenschoten 

> this is assuming the Raft log append and the HardState update are atomic

Yes. This needs to be fixed.

**Comment by tbg** [comment]
> L1. the (Append) invariant ensures that no replica may hold more than one uncommitted/implicitly committed config change in its log. The sync you require ensures that this is true even after a restart [1].

We just ran into this again in https://github.com/cockroachdb/cockroach/pull/38380. Let's say we can't write to the Raft log and HardState durably in one atomic operation. Which way to do it?

We can't write to the Raft log and then the HardState because that just straight-up violates (Append). We could write to the HardState first and then append, I think, if we tolerated `Committed > LastIndex` (and just treated it as LastIndex) instead. That might be the way to go but I want to think about it some more.

**Comment by bdarnell** [comment]
I've always thought that the panicking around `Committed > LastIndex` was overly strict, but relaxing that constraint does run the risk of silently losing durability. Today it's only really a problem in single-node clusters (in which case we can safely assume that if `Committed > LastIndex`, the operation failed and completion was not reported back to the client), but if we relax the constraint we may later end up in a case where a follower receives the wrong commit index, doesn't catch it, and we think we've committed something that's not durable in enough places.

That said, I think writing HardState before logs makes more sense than the other way around, so I'd be in favor of relaxing this constraint to make this work.

**Comment by tbg** [comment]
> Today it's only really a problem in single-node clusters

This isn't actually true. If a node is catching up on the log, it'll receive batches of Entries that are immediately fully committed in the same Ready. So persisting first the HardState and then separately the Ready creates this problem no matter the replication factor.

> That said, I think writing HardState before logs makes more sense than the other way around, so I'd be in favor of relaxing this constraint to make this work.

Curious why you think it makes more sense that way. Wouldn't they identically be independent, but the commit index happens to suggest doing the HardState second? Ironically the Raft readme itself gets this wrong, I'll clean that up at some point.

I chatted about (Append) with @nvanbenschoten a few days ago and we agreed to hide the details from the app as much as possible. Conf changes aren't performance critical so we can emit some suboptimal `Ready`s to simplify the semantics. As a result, I won't try reversing the HardState/append order, but if you have reasons for preferring that I'll consider it.

Basically what we should do is that whenever there's a ConfChange that would be emitted in the next Ready, we instead split this up into

1. if `Ready.Commit >= ents[0].Index`: emit `Ready{Commit: ents[0].Index-1, MustSync: true}`
2. emit the remaining Ready, up to but excluding the *second* ConfChange in its Entries (cutting of Commit appropriately) if it exists.
3. back to 1. with anything left over by 2.

Step 1 durably makes any prior ConfChange committed without complicating the relationship between HardState/Append (we could append the prefix of entries excluding the ConfChange, but this seems simpler). Step 2 and 3 append the ConfChanges one at a time, each time making sure the previous one is durably known committed before appending the next.

The steps above ignore that the Ready also contains other data such as messages to be sent and entries to be applied. We need to make sure to clamp CommittedEntries appropriately, and we also need to decide when to send the messages. It's "safest" to send them only in the last Ready due to all of the optimizations around sending messages before persisting the corresponding entries, so that's what I will look into (it would be more convenient to send them out with the first Ready, but I really think this breaks our optimizations in CRDB).

That way, the app can persist the Entries before the HardState and we still retain `(Append)` without even telling the app about it; this will just work if the app correctly interprets `MustSync`.

Examples:

First, the common case: we receive a new commit index 53 and some new entries 50..60, among them a (yet uncommitted) ConfChange at index 55. We'll emit two Readys:

- Ents=[] Commit=49 MustSync=true
- the original ready

Note that there must not be another ConfChange at any index > 53 or the leader messed up its half of `(Append)` and gave us two "not known committed" ConfChanges. However, there could be one at, say, index 52 in which case the steps becomee the following (MustSync is always true)

- Ents=[] Commit=49
- Ents[50,51,52] Commit=52
- Ents=[] Commit=52
- Ents[53,...,60] Commit=53

In the last step, if the app crashes between appending Ents[53..60] and the Commit index, we'll lose the commit index but it will only regress to 52, preserving the knowledge that the first ConfChange at 52 is committed.

Another example: 50..70 with ConfChanges at 55, 60, 65, 70; Commit=67

- Ents=[] Commit=49
- Ents=[50..59] Commit=59
- Ents=[] Commit=59 (this is redundant, but may not be worth avoiding)
- Ents=[60..64] Commit=64
- Ents=[] Commit=64 (ditto)
- Ents=[65..69] Commit=67
- Ents=[70]

**Comment by bdarnell** [comment]
> Curious why you think it makes more sense that way. Wouldn't they identically be independent, but the commit index happens to suggest doing the HardState second?

The HardState is used for two purposes that are only loosely connected. There's the Term and Vote which must be persisted and are unrelated to the log, and there's the Commit which (prior to this proposal) had less strict durability requirements. My mental model is that the ideal order of operations would be 1. write term+vote 2. append to log 3. write commit index. Bundling the term+vote+commit into HardState is an optimization to avoid an extra write but it complicates the order of operations.

The specific complication with writing HardState second is that the log also contains term numbers. What if we end up with a higher term in a log entry than we have in our persisted HardState?

**Comment by tbg** [comment]
Reminder to self: we'll also want to make sure that a follower does not vote if there could be newer unapplied (known committed) configuration in the log. This is because the candidate could be arbitrarily behind (perhaps it was not involved in any commit quorum for quite a while). If it receives votes from other nodes that would not vote for it under the config under which they would campaign, that behind node might consider itself winner of the election.

**Comment by tbg** [comment]
Continuing discussion with @hicqu from https://github.com/etcd-io/etcd/issues/11284 here:

> @tbg thanks for your replay! Seems you worry about rolling update a Raft cluster. How about making the new behavior as an option? Only if it's enabled configuration changes become effective on received, otherwize on applied, just like now. And we can add a rolling update interface on Storage interface to document how to update a cluster to enable the feature. According to our research, the update is safe, what applications need to do is just read all received but not applied Raft logs and read configuration changes in them when restart.

My concern is less that this can't be made work, but that it takes a production use case of `etcd/raft` to work out the kinks. If I understand correctly, you're using "proper" joint consensus in TiKV already (?) and so you are likely aware of most of the problems (you had upgrade issues to worry about as well, correct?). Yet, I just worry that there will end up being more work that is necessary than you're able to contribute (since you're not using etcd/raft yourself - correct?), and that we're going to get stuck awkwardly in-between. For example, intuitively I feel that we shouldn't try to maintain two mechanisms side by side, simply because I suspect that this will lead to a lot of confusion in the code (this may not be true). But then we force all apps into a more complicated contract (ApplyConfChange may now be called for config changes that end up being rolled back, but existing apps have sometimes attached triggers to these, etc) and in particular we'll be forced to make changes to `etcdserver` and roll back some weird things they do there. (If "both APIs" can be made work first, I'd prefer that, to avoid buying into the new mechanism too deeply).

That isn't to say that I am not interested in the improvement - I am - just that at this point I can't give any particular commitment to reviewing, improving, or merging the work. However, if this isn't too off-putting, we could scope out the work to get a more concrete picture of what changes would be entailed. For example, how would the `Node` interface have to change, which areas in the code would need to change, etc -- all of this could be demonstrated in a prototype. Even if the result is that we won't follow through at the moment, this will a be a good exercise to set us up for success once we do want to follow through.

**Comment by tbg** [comment]
FYI, in CockroachDB we are now working around this problem by not removing voters directly. We demote them first (i.e. turn them into learners) and then remove them. That avoids the unavailability when the leader crashes.

**Comment by hicqu** [comment]
@tbg thanks for your effort! I believe it's helpful, however maybe can't resolve the problem at root.

Suppose there is a Raft group with peers `A, B, C and D`. In one moment their configurations could be
```
A: (B, C, D)
B: (A, B, C, D) && (B, C, D), learners_next: (A)
C: (A, B, C, D) && (B, C, D), learners_next: (A)
D: (A, B, C, D) && (B, C, D), learners_next: (A)
```
A has leaving joint and response the proposer tht A is removed. However B, C, D don't know this.
Then A and B fail, C and D still can't elect a leader.

I'm also trying to find a solution for this case. Currently my thought is **making `leaving joint` effective on received**. So the problem can be resolved perfectly, and seems the compatibility won't be impacted too much.

What do you think about it?

**Comment by tbg** [comment]
In your example, A is two configurations ahead of B, C, D, which should not be possible if `(Append)` from https://github.com/etcd-io/etcd/issues/7625#issuecomment-489232411 holds. A quorum of B,C,D will know that they can switch to `(B, C, D) + Learner(A)` before campaigning, so they can elect a leader. Am I missing something?

**Comment by hicqu** [comment]
Suppose the Raft group enters joint at index `10`, and it's leaving joint at index `11`. So their configuration and states could be:
```
A: voters: (B, C, D), last_index: 11, committed: 11, applied: 11
B: voters: (B, C, D), last_index: 11, committed: 10, applied: 10
C: voters: (B, C, D), last_index: 11, committed: 10, applied: 10
D: voters: (B, C, D), last_index: 11, committed: 10, applied: 10
```
Seems A is only one configurations ahead of B, C and D.
And B, C, D maybe can't apply to `11` forever, because A hasn't casted any `commit to 11` to them before fail.

**Comment by tbg** [comment]
Right, but what's your example? A is still around until it gets removed. If you're saying a goes down, while another node also goes down, then yes you could lose quorum, but you started out with four nodes where that is also true, and if you wanted to know that it stopped being true, you could wait for a majority to have applied the latest change (ugly, but it works).

The thing I really want to avoid is having anything funky happening when replacing a node, i.e. going from `A B C` to `A B D`. Without the intermediate learner step, an example similar to 2) from your initial post shows that the leaseholder failing at the "right" moment will wedge the raft group because the removal of C being processed on C can also lead to C going "down", as in, not responding to requests any more.

**Comment by bdarnell** [comment]
@tbg What's left to do here? We've been using joint consensus in CRDB for a while now. Is the only open item to allow removal of a voter directly without downgrading to learner first?
