### ISSUE TITLE
Rebalance watchers

### ISSUE THREAD

**Issue by cw9** [etcd-io/etcd#7683]
The number watchers in the cluster is relatively well balanced among all the etcd nodes in normal state. But when one node dies, the watchers connected to the restarting node will be "moved" to the rest of the cluster because of clients retrying, but when the dead node came back to the cluster, there is no way to rebalance the whole cluster, the node could not take the load from other overloaded nodes in the cluster.

**Comment by xiang90** [comment]
@cw9 this is something we would like to resolve, at etcd level or at least a clear documentation. it would be great if you can help to explore the options a little bit. helping us to see how similar systems handle this: zookeeper, mongodb, cassandra etc..

thank you!

**Comment by mcginne** [comment]
We observe similar behaviour if we create long lived connections that do puts/gets - existing connections never get moved to the recovered node (unless another node is restarted). For these connections this can be managed by periodically recreating them - but I wondered if there was any likelihood/desire to handle this at etcd client level?

**Comment by xiang90** [comment]
@mcginne yes. as i mentioned early, we need to define a rebalancing policy. it would be helpful if you can propose one. (gRPC might have its own defined policy we can follow? what do zookeeper and other similar system do?)

**Comment by raoofm** [comment]
@xiang90 I was able to do some research on how zk does this for reconfiguration rather than reboot but it is a similar concept that can be applied to reboot as well.

zk made the decision that this workload should be on the clients and not on the servers, so they should subscribe to cluster/config and see the change in the server list and accordingly rebalance the clients. The rebalancing strategy is that the clients would sleep for a random(0 to 5 seconds) time and wake up to get the new server list with number of clients and then migrate. This was done to avoid mass migration of the clients.

We can use the similar concept of reconfiguration and apply to active nodes in the cluster.

**Comment by raoofm** [comment]
@xiang90 @heyitsanthony Details can be found in [this ](https://www.usenix.org/system/files/conference/atc12/atc12-final74.pdf)paper in section 4 and 5.

**Comment by raoofm** [comment]
Also 

> When a ZooKeeper cluster is started, if each client is given the same connection string (list of servers), the client will randomly choose a server in the list to connect to, which makes the expected number of client connections per server the same for each of the servers. We implemented a method that preserves this property when the set of servers changes through reconfiguration. See Sections 4 and 5.1 in the paper.
In order for the method to work, all clients must subscribe to configuration changes (by setting a watch on /zookeeper/config either directly or through the getConfig API command). When the watch is triggered, the client should read the new configuration by invoking sync and getConfig and if the configuration is indeed new invoke the updateServerList API command. To avoid mass client migration at the same time, it is better to have each client sleep a random short period of time before invoking updateServerList.

**Comment by heyitsanthony** [comment]
@raoofm I've never seen this behavior from a zookeeper client. It looks like this is a 3.5 feature which is still in alpha. Are there any examples of this actually being used in practice?

**Comment by heyitsanthony** [comment]
Namely, I'm skeptical of a design announced four years ago that still is not in production.

**Comment by raoofm** [comment]
> It looks like this is a 3.5 feature which is still in alpha.
Yeah may be. I went by the documentation for 3.4(as per title) and it still has it. Strangely though the same documentation talks about upgrading to 3.5, so I'm not sure if it is a 3.4 or a 3.5.

Check the below link that talks about it with a basic client example that I copied below.

https://zookeeper.apache.org/doc/trunk/zookeeperReconfig.html#ch_reconfig_rebalancing

`public void process(WatchedEvent event) {`
`    synchronized (this) {`
`        if (event.getType() == EventType.None) {`
`            connected = (event.getState() == KeeperState.SyncConnected);`
`            notifyAll();`
`        } else if (event.getPath()!=null &&  event.getPath().equals(ZooDefs.CONFIG_NODE)) {`
`            // in prod code never block the event thread!`
`            zk.sync(ZooDefs.CONFIG_NODE, this, null);`
            `zk.getConfig(this, this, null);`
       ` }`
    `}`
`}`
`public void processResult(int rc, String path, Object ctx, byte[] data, Stat stat) {`
`    if (path!=null &&  path.equals(ZooDefs.CONFIG_NODE)) {`
 `       String config[] = ConfigUtils.getClientConfigStr(new String(data)).split(" ");   // similar to config -c`
 `       long version = Long.parseLong(config[0], 16);`
`        if (this.configVersion == null){`
`             this.configVersion = version;`
`        } else if (version > this.configVersion) {`
`            hostList = config[1];`
 `           try {`
 `               // the following command is not blocking but may cause the client to close the socket and`
    `            // migrate to a different server. In practice its better to wait a short period of time, chosen`
`                // randomly, so that different clients migrate at different times`
   `             zk.updateServerList(hostList);`
`            } catch (IOException e) {`
 `               System.err.println("Error updating server list");`
  `              e.printStackTrace();`
 `           }`
  `          this.configVersion = version;`
`} } }`

**Comment by heyitsanthony** [comment]
@raoofm It's definitely 3.5. Check the API docs:
* https://zookeeper.apache.org/doc/r3.4.9/api/org/apache/zookeeper/ZooKeeper.html no `getConfig`
* https://zookeeper.apache.org/doc/r3.5.1-alpha/api/org/apache/zookeeper/ZooKeeper.html has `getConfig`

I haven't seen a single zookeeper project using this feature when developing zetcd. I don't think it's something any actually uses or cast as a successful solution to this problem.

**Comment by raoofm** [comment]
Yep 3.5
