### ISSUE TITLE
Detailed guide for hacking on etcd: write one

### ISSUE THREAD

**Issue by pgburt** [etcd-io/etcd#7828]
# Feature request

A [Twitter user](https://twitter.com/andrew_j_stone/status/857454399748231168) writes:
> I'm looking for an architecture overview and how to start hacking without having to read all the code, like this:
https://github.com/andrewjstone/rabble/blob/master/doc/architecture.md

Do we know of any guides for getting started / hacking with etcd?

**Comment by heyitsanthony** [comment]
There's a place in the documentation where the internal architecture details should go, but no one has written it yet because there is no time and it's one more thing that would need to be actively maintained.

Probably worth noting that the user provided a document he wrote himself for a single-contributor repo that only has 26 commits. What do large projects do?

**Comment by gyuho** [comment]
Yeah it will be a lot of much work to keep it up-to-date. Instead, one can check out https://godoc.org/github.com/coreos/etcd. I think this is the great start point.

**Comment by gyuho** [comment]
We will start documenting internals of etcd https://etcd.readthedocs.io/en/latest.
