### ISSUE TITLE
etcdctl: arbitrary protobuf/json serialization/deserialization

### ISSUE THREAD

**Issue by heyitsanthony** [etcd-io/etcd#8460]
Binary data is inconvenient to process directly from etcdctl. An `--encoding` mode could help by accepting a protobuf definition (+ other formats like gob?) and use it to interpret the key value.

To decode protobuf into json: `etcdctl --encoding=whatever.proto get /abc`
To encode json into protobuf: `etcdctl --encoding=whatever.proto put /abc "some-json"`

Compile-time dependencies could be kept to a minimum by calling out to go+protoc to generate the parser.

/cc @jpbetz

**Comment by jpbetz** [comment]
This sounds useful. Maybe it should be generalized to accept any encode/decode program? E.g.

```sh
etcdctl --decoder ./mydecoder get /abc
etcdctl --encoder ./myencoder put /abc "some-json" 
```

This keeps etcd agnostic of the encoding schemes developers choose. It does add some complexity to etcdctl because is has to deal with sub process execution somehow, but so do tools like `git bisect`, so maybe it would be acceptable?

To give a bit of background, the kubernetes binary data encoding is fairly involved:

- Byte array prefixed with four bytes: "k8s\0"
- The remainder of the array is a [Unknown](https://github.com/kubernetes/apimachinery/blob/dc1f89aff9a7509782bde3b68824c8043a3e58cc/pkg/runtime/generated.proto#L113) protobuf
- Unknown.typeMeta can be used to determine which protobuf type Unknown.raw contains

I decoded it by hand using protoc and etcdctl once, it was tedious, hence the desire to build a tool (https://github.com/kubernetes/kubernetes/issues/45974).

**Comment by heyitsanthony** [comment]
@jpbetz yes, there's already precedent for external executables in the migration command. `etcdctl` could detect if +x is set on the encoder/decoder to determine whether it's an executable or a schema.

**Comment by jpbetz** [comment]
Great, I'll have a look at migration and work on getting a PR written up for this.

**Comment by heyitsanthony** [comment]
@jpbetz if etcdctl just needs multi-line on raw binary values, it'd probably be better at this point to support `--print-value-only -w protobuf` + pipe instead of adding encode/decode executables
