### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by ddollar** [etcd-io/etcd#872]
Left an etcd cluster running for a little over a week. When I came back all hosts had near 100% utilization from etcd and spewing this log message:

```
Jul 02 12:22:31 ip-10-0-3-246 etcd[668]: 2014/07/02 12:22:31 http: Accept error: accept tcp [::]:7001: too many open files; retrying in 1s
Jul 02 12:22:31 ip-10-0-3-246 etcd[668]: 2014/07/02 12:22:31 http: Accept error: accept tcp [::]:4001: too many open files; retrying in 1s
Jul 02 12:22:32 ip-10-0-3-246 etcd[668]: 2014/07/02 12:22:32 http: Accept error: accept tcp [::]:7001: too many open files; retrying in 1s
Jul 02 12:22:32 ip-10-0-3-246 etcd[668]: 2014/07/02 12:22:32 http: Accept error: accept tcp [::]:4001: too many open files; retrying in 1s
Jul 02 12:22:33 ip-10-0-3-246 etcd[668]: 2014/07/02 12:22:33 http: Accept error: accept tcp [::]:7001: too many open files; retrying in 1s
Jul 02 12:22:33 ip-10-0-3-246 etcd[668]: 2014/07/02 12:22:33 http: Accept error: accept tcp [::]:4001: too many open files; retrying in 1
```

**Comment by tsouza** [comment]
Hello,

Is there any solution to this? I'm running a 3 node cluster on EC2 with etcd 0.4.7 and latest coreos image. After running "netstat | grep CLOSE_WAIT | wc -l" I get a count of more then 1000. How to fix this?

Thanks

**Comment by yichengq** [comment]
@tsouza The error indicates that there are too many concurrent clients in a short window(which depends on how fast tcp socket is closed). etcd 2.0 does handle the timeout stuffs better, and i suggest to give it a try.

**Comment by tsouza** [comment]
@yichengq thanks for the tip! I'm using CoreOS official EC2 image. How do I upgrade to etcd 2.0?

Thanks!

**Comment by yichengq** [comment]
@tsouza You can download it at github, or wait for etcd2.0 in CoreOS image release, which will happen soon.

**Comment by hookenz** [comment]
I guess there is a lot of etcd 2 testing going on.  It hasn't made it even to alpha CoreOS build yet.

For me it's a show stopping bug that's prevented me from using etcd.

**Comment by hookenz** [comment]
I've been looking at the code for etcd 0.4* which uses goraft library.  goraft uses net/http.  Newer versions of etcd apparently use a newer implementation of goraft.  I'm interested in this one because etcd2 isn't even in alpha channel for CoreOS yet.

What I am seeing is many sockets stuck in either CLOSE_WAIT or FIN_WAIT2.  FIN_WAIT2 is a state where the server has closed the socket, but has not received an acknowledgement from the client.  This is likely a bug in net/http. or goraft.  I don't really understand the golang enough to see what's happening.

IMHO if the server is going to call close, it should do an abortive one.  Otherwise the heartbeats will build.
But I don't understand why each etcd server doesn't just keep a single connection open forever, maybe it is? can't really tell.  Time I learned golang I think.

**Comment by yichengq** [comment]
@hookenz etcd 2.0 is a really good-design one. You can check the raft impl here: https://github.com/coreos/etcd/blob/master/raft/doc.go

For testing, we have unit testing, integration testing(https://github.com/coreos/etcd/tree/master/integration), and functional testing(https://github.com/coreos/etcd/tree/master/tools/functional-tester). We also have plan for more testing to ensure correctness.

The etcd 2.0 uses stream that exists for long time, so it should not have this problem for communication between etcd members.
