### ISSUE TITLE
clientv3: deprecate grpc.ErrClientConnClosing

### ISSUE THREAD

**Issue by gyuho** [etcd-io/etcd#9304]
`grpc.ErrClientConnClosing` is being deprecated at https://github.com/grpc/grpc-go/pull/1854.

https://github.com/coreos/etcd/blob/fe94f8f53af1c2ab684df713bf7e084ef3f1c675/clientv3/client.go#L550-L551

Just to not forget when we rewrite clientv3 balancer with new gRPC versions.

**Comment by dfawley** [comment]
Note that by the [grpc-go versioning policy](https://github.com/grpc/grpc-go/blob/master/Documentation/versioning.md), we cannot and will not remove this, as it would break backward compatibility.

However, it's possible small behavior changes will be necessary that cause us to return other errors instead of ErrClientConnClosing in various circumstances, so you should not typically rely on any specific errors unless the godoc is explicit about what will be returned.

**Comment by gyuho** [comment]
@dfawley Thanks for update! We will keep that in mind.
