### ISSUE TITLE
clientv3: enable KeepAlive ping by default

### ISSUE THREAD

**Issue by gyuho** [etcd-io/etcd#9495]
Client keep-alive ping is essential for high client availability under network faults.

https://github.com/coreos/etcd/blob/583fda72403f4202e7a30a34d950093151e3697a/clientv3/config.go#L36-L42

Currently, disabled by default, while many Kubernetes production deployments benefited from this feature enabled. Kubernetes enables this by default as well https://github.com/kubernetes/kubernetes/blob/06e3fefc2153637daa65657025794b7dc27f6f33/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go#L32-L57.

We should find the right default value and enable it by default in 3.4.

/cc @jpbetz

**Comment by yudai** [comment]
We may want to revisit the default value of server side keep alive configurations and align them with the client side configuration.

For example, the default server side interval is `2h` now, but it could be too long to detect closed(broken) sockets by clients due to client side keep alive timeouts.

https://github.com/coreos/etcd/blob/473793be1f9e02b1416071e29fe13aa2dd59b9e0/etcdmain/help.go#L74
