### ISSUE TITLE
Add a caching layer for password auth

### ISSUE THREAD

**Issue by joelegasse** [etcd-io/etcd#9713]
Continuing the conversation from #9615, I think a better approach for reducing the CPU overhead of authenticating with a password that wouldn't reduce the difficulty of brute-forcing the passwords should the database leak would be to cache successful authentication requests.

My proposed scheme would be:
- Strongly recommend `bcrypt.DefaultCost` as the difficulty parameter
- The first time a user successfully authenticates against the bcrypt hash, do the following
  1. Generate a random salt
  2. Hash the salted password with a basic hash (SHA256, for example)
  3. Cache `(bcrypt hash, salt, hash result)` for the user
- Every time a user connects and they have an entry in the cache, do the following:
  - If the current bcrypt hash matches the cached bcrypt hash, hash the password with the salt (<1us) to authenticate the user.
  - If the current bcrypt hash differs from the cached bcrypt hash, remove the cache entry and proceed with the normal (slow, ~60ms) bcrypt authentication, caching on success.
- (Maybe?) Preemptively disseminate `(bcrypt hash, salt, hash result)` between the nodes (in-memory only) to mitigate the cost of having to take the bcrypt time penalty on each server in the cluster.
- (Maybe?) Preemptively purge cache entries when a user's password is changed (infrequent).

Some benefits of this include:
- The bcrypt cost is maintained at the recommended difficulty in the event of a database (on-disk) breach.
- Subsequent authentication attempts to nodes with a current cache entry are fast, and do not steal all the CPU in a busy cluster.
- The additional risk of an adversary acquiring the salt+hash is the same as an adversary being able to read the process' memory, in which case the plaintext password would also be accessible.

/cc @jxuan @gyuho @ericchiang @mitake

**Comment by ericchiang** [comment]
This seems like a fine solution. It's low overhead, doesn't introduce new APIs. etc.

On a side note, bcrypt is supposed to be a bottle neck, and the fact that we're working around that probably indicates that bcrypt isn't a good fit for this use case. As I mentioned in the original issue (https://github.com/coreos/etcd/issues/9615), I think a different kind of credential would be a more wholistic solution. Random values, signed random values, whatever. Just not bcrypt.

**Comment by jxuan** [comment]
I like this idea, but I am afraid that it can be very complex to share in memory cache among etcd server nodes. I like ericchiang's comments here.

Several other things I'd like to suggest to alleviate this problem:
1. Clients do not use a fixed order to connect to etcd server nodes. Each client should choose a random server node to connect to each time. Otherwise, if all clients share the same list of etcd nodes, it can bring down the first node in the list during a re-election if there are a large number of clients.
2. Should uses JWT token instead of simple token. In case of a re-election, if the client presents a valid JWT token, the client should connect without having to go through the bcrypt algorithm on the server side.
