### ISSUE TITLE
Configure problem: difference between --listen-addr and --advertise-client-url in gRPC-proxy mode

### ISSUE THREAD

**Issue by xjas** [etcd-io/etcd#9927]
@gyuho I recently encountered some tough problems and had no idea.

First, gRPC-proxy is not used and application works fine.

Then I use gRPC-proxy, usage is like this:
`ETCDCTL_API=3   ./etcd grpc-proxy start  --cacert=./config/ssl/ca.pem  --cert=./config/ssl/client.pem  --key=./config/ssl/client-key.pem --trusted-ca-file=./config/ssl/ca.pem --cert-file=./config/ssl/client.pem --key-file=./config/ssl/client-key.pem --endpoints 100.50.129.77:2379  --listen-addr 100.50.129.77:23795  --advertise-client-url 100.50.129.77:23780`

The application connected gRPC-proxy well at first, but then it disconnected from the gRPC-proxy. Using tcpdump to capture the packet, I found this.

07.beta is client and 01.beta is server.
![1531819259024-image](https://user-images.githubusercontent.com/22660757/42808405-d7d4ccdc-89e5-11e8-8e52-234aed895f56.png)

My application tried to connect port 23780, and it fails of course. Then everything is out of control, it disconnected from the normal port 23795 and then tried to connect port  23780 again and again.I don't know what happens. 

The flag `--advertise-client-url` completely confuses me now. May I have your suggestions? Thanks in advance.

**Comment by hexfusion** [comment]
@xjas `--advertise-client-url` allows you advertise an IP address or domain name and port while `--listen-addr` is the ip address and port the proxy will listen on. If you wanted to `--listen-addr 100.50.129.77:23795` you need to advertise the same ip:port. Because you set `--advertise-client-url 100.50.129.77:23780` the application will try to instead connect to the advertised port 23780 but the proxy is not listening to that port so it fails.

In short you can't advertise a service that does not exist.

```
$ etcdctl --endpoints 127.0.0.1:23790 member list -w table
+----+---------+-----------------------+------------+------------------------------------+
| ID | STATUS  |         NAME          | PEER ADDRS |            CLIENT ADDRS            |
+----+---------+-----------------------+------------+------------------------------------+
|  0 | started | localhost.localdomain |            | http://etcd1.hexfusion.local:23790 |
+----+---------+-----------------------+------------+------------------------------------+

```
